(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMEFT",
  Authors -> "A. Dedes, J. Rosiek, M. Ryczkowski",
  Version -> "4.03",
  Date -> "01. 04. 2026",
  Emails -> "janusz.rosiek@fuw.edu.pl",
  URLs -> "URL: www.fuw.edu.pl/smeft"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}, {CP, 0}, {UFO, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "A",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "g",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mvdiag },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mldiag },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mudiag },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mddiag },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MG0,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MGP,
    Indices -> {} },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]A",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]Z",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "\[Eta]Wp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "\[Eta]Wm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]G",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

S[31] == {
    QuantumNumbers -> {-1/3*Q},
    Indices -> {Index[Generation], Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    PropagatorLabel -> xduu,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MX }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
mvdiag[ 1 ] := 0;
mvdiag[ 2 ] := 0;
mvdiag[ 3 ] := 0;
mldiag[ 1 ] := MLE;
mldiag[ 2 ] := MLM;
mldiag[ 3 ] := MLT;
mudiag[ 1, _ ] := MQU;
mudiag[ 1 ] := MQU;
mudiag[ 2, _ ] := MQC;
mudiag[ 2 ] := MQC;
mudiag[ 3, _ ] := MQT;
mudiag[ 3 ] := MQT;
mddiag[ 1, _ ] := MQD;
mddiag[ 1 ] := MQD;
mddiag[ 2, _ ] := MQS;
mddiag[ 2 ] := MQS;
mddiag[ 3, _ ] := MQB;
mddiag[ 3 ] := MQB;
MH[ ___ ] := MH;
MG0[ ___ ] := MG0;
MGP[ ___ ] := MGP;
MgZ[ ___ ] := MgZ;
MgW[ ___ ] := MgW;
MX[ ___ ] := MX;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ S[31, {__}] ] := TheLabel[S[31]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] ] == {{((-3*I)*2^(1/4)*(Gf^2*Hmass^2 - Cphi*Lam))/Gf^(3/2), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-3*I)*Sqrt[2]*(Gf^2*Hmass^2 - 6*Cphi*Lam))/Gf, 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] ] == {{((45*I)*2^(3/4)*Cphi*Lam)/Sqrt[Gf], 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] , S[1] ] == {{(90*I)*Cphi*Lam, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc5[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {I*gc5[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc6[e1x2, e2x2], 0}, {0, 0}, {I*gc6[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc7[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {I*gc7[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc8*SUNF[e1x2, e2x2, e3x2]), 0}, {gc8*SUNF[e1x2, e2x2, e3x2], 0}, {gc8*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc8*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc8*SUNF[e1x2, e2x2, e3x2]), 0}, {gc8*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc9*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc9*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc9*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc10*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {I*gc10*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc11*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {I*gc11*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc12*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {0, 0}, {I*gc12*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {0, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc13, 0}, {I*gc13, 0}, {I*gc13, 0}, {(-I)*gc13, 0}, {(-I)*gc13, 0}, {I*gc13, 0}},

C[ S[1] , V[3] , -V[3] ] == {{(2*I)*2^(1/4)*Sqrt[Gf]*Wmass^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{(2*I)*Sqrt[2]*Gf*Wmass^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc16, 0}, {(-I)*gc16, 0}, {(2*I)*gc16, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc17, 0}, {I*gc17, 0}, {I*gc17, 0}, {(-I)*gc17, 0}, {(-I)*gc17, 0}, {I*gc17, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc18, 0}, {(-I)*gc18, 0}, {(2*I)*gc18, 0}},

C[ -F[2, {e1x2}] , -F[3, {e2x2, e2x3}] , S[31, {e3x1, e3x2, e3x3}] ] == {{I*gc19*IndexDelta[e1x2, {{-F[2, {e1x2}], 1}, {-F[3, {e2x2, e2x3}], 2}, {S[31, {e3x1, e3x2, e3x3}], 3}}[[First[[{3, 2}]],1]][[2,1 + {}[[1]]]]]*IndexDelta[e2x2, {{-F[2, {e1x2}], 1}, {-F[3, {e2x2, e2x3}], 2}, {S[31, {e3x1, e3x2, e3x3}], 3}}[[First[[{3, 1}]],1]][[2,1 + {}[[1]]]]]*IndexDelta[e2x3, e3x3], 0}, {0, 0}, {0, 0}, {0, 0}},

C[ F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[31, {e3x1, e3x2, e3x3}] ] == {{0, 0}, {0, 0}, {I*Lam*Cduu3[e1x2, e2x2, {{F[4, {e1x2, e1x3}], 1}, {F[3, {e2x2, e2x3}], 2}, {S[31, {e3x1, e3x2, e3x3}], 3}}[[First[[{3, 1}]],1]][[2,1 + {}[[1]]]], {{F[4, {e1x2, e1x3}], 1}, {F[3, {e2x2, e2x3}], 2}, {S[31, {e3x1, e3x2, e3x3}], 3}}[[First[[{3, 2}]],1]][[2,1 + {}[[1]]]]]*Eps[e1x3, e2x3, e3x3], 0}, {0, 0}},

C[ F[2, {e1x2}] , F[3, {e2x2, e2x3}] , -S[31, {e3x1, e3x2, e3x3}] ] == {{0, 0}, {0, 0}, {I*Lam*MX^2*UFOOrder*IndexDelta[e1x2, {{F[2, {e1x2}], 1}, {F[3, {e2x2, e2x3}], 2}, {-S[31, {e3x1, e3x2, e3x3}], 3}}[[First[[{3, 2}]],1]][[2,1 + {}[[1]]]]]*IndexDelta[e2x2, {{F[2, {e1x2}], 1}, {F[3, {e2x2, e2x3}], 2}, {-S[31, {e3x1, e3x2, e3x3}], 3}}[[First[[{3, 1}]],1]][[2,1 + {}[[1]]]]]*IndexDelta[e2x3, e3x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , -F[3, {e2x2, e2x3}] , -S[31, {e3x1, e3x2, e3x3}] ] == {{I*gc22[e1x2, e1x3, e2x2, e2x3, e3x1, e3x2, e3x3], 0}, {0, 0}, {0, 0}, {0, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc23, 0}, {I*gc23, 0}, {I*gc23, 0}},

C[ S[1] , V[2] , V[2] ] == {{(2*I)*2^(1/4)*Sqrt[Gf]*Zmass^2, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{(2*I)*Sqrt[2]*Gf*Zmass^2, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc26, 0}, {(-I)*gc26, 0}, {(2*I)*gc26, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc27*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {I*gc27*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc28*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {I*gc28*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc29*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc30[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc31[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc32*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {((2*I)*gc33*(Wmass - Zmass)*(Wmass + Zmass)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(2*Wmass^2 + Zmass^2), 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc34*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {((-2*I)*gc34*(Wmass - Zmass)*(Wmass + Zmass)*IndexDelta[e1x2, e2x2])/(-2*Wmass^2 + Zmass^2), 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc35*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}, {((-4*I)*gc35*(Wmass - Zmass)*(Wmass + Zmass)*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3])/(-4*Wmass^2 + Zmass^2), 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc36*IndexDelta[e1x2, e2x2], 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[2, {e3x2}] , F[2, {e2x2}] , F[2, {e4x2}] ] == {{I*gc37*(Cl4phi2n1[e1x2, e4x2, e3x2, e2x2] + Cl4phi2n1[e3x2, e2x2, e1x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc37*(Cl4phi2n1[e1x2, e2x2, e3x2, e4x2] + Cl4phi2n1[e3x2, e4x2, e1x2, e2x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[2, {e3x2}] , F[2, {e2x2}] , F[2, {e4x2}] , S[1] ] == {{I*gc38*(Cl4phi2n1[e1x2, e4x2, e3x2, e2x2] + Cl4phi2n1[e3x2, e2x2, e1x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc38*(Cl4phi2n1[e1x2, e2x2, e3x2, e4x2] + Cl4phi2n1[e3x2, e4x2, e1x2, e2x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[2, {e3x2}] , F[2, {e2x2}] , F[2, {e4x2}] , S[1] , S[1] ] == {{I*gc39*(Cl4phi2n1[e1x2, e4x2, e3x2, e2x2] + Cl4phi2n1[e3x2, e2x2, e1x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc39*(Cl4phi2n1[e1x2, e2x2, e3x2, e4x2] + Cl4phi2n1[e3x2, e4x2, e1x2, e2x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[1, {e3x2}] , F[2, {e2x2}] , F[1, {e4x2}] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc40[e1x2, e3x2, e2x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[1, {e3x2}] , F[2, {e2x2}] , F[1, {e4x2}] , S[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc41[e1x2, e3x2, e2x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , -F[1, {e3x2}] , F[2, {e2x2}] , F[1, {e4x2}] , S[1] , S[1] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc42[e1x2, e3x2, e2x2, e4x2], 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1, {e1x2}] , -F[1, {e3x2}] , F[1, {e2x2}] , F[1, {e4x2}] ] == {{I*gc43*(Cl4phi2n1[e1x2, e4x2, e3x2, e2x2] + Cl4phi2n1[e3x2, e2x2, e1x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc43*(Cl4phi2n1[e1x2, e2x2, e3x2, e4x2] + Cl4phi2n1[e3x2, e4x2, e1x2, e2x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1, {e1x2}] , -F[1, {e3x2}] , F[1, {e2x2}] , F[1, {e4x2}] , S[1] ] == {{I*gc44*(Cl4phi2n1[e1x2, e4x2, e3x2, e2x2] + Cl4phi2n1[e3x2, e2x2, e1x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc44*(Cl4phi2n1[e1x2, e2x2, e3x2, e4x2] + Cl4phi2n1[e3x2, e4x2, e1x2, e2x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ -F[1, {e1x2}] , -F[1, {e3x2}] , F[1, {e2x2}] , F[1, {e4x2}] , S[1] , S[1] ] == {{I*gc45*(Cl4phi2n1[e1x2, e4x2, e3x2, e2x2] + Cl4phi2n1[e3x2, e2x2, e1x2, e4x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {I*gc45*(Cl4phi2n1[e1x2, e2x2, e3x2, e4x2] + Cl4phi2n1[e3x2, e4x2, e1x2, e2x2]), 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc5[e1x2_, e2x2_] -> -(2^(1/4)*Sqrt[Gf]*fmd[e1x2, e2x2]),
     gc6[e1x2_, e2x2_] -> -(2^(1/4)*Sqrt[Gf]*fml[e1x2, e2x2]),
     gc7[e1x2_, e2x2_] -> -(2^(1/4)*Sqrt[Gf]*fmu[e1x2, e2x2]),
     gc8 -> 2*Sqrt[aS]*Sqrt[Pi],
     gc9 -> -4*aS*Pi,
     gc10 -> (2*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc11 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc12 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc13 -> (-2*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc16 -> (4*Sqrt[2]*Gf*Wmass^2*(Wmass^2 - Zmass^2))/Zmass^2,
     gc17 -> (-2*2^(1/4)*Sqrt[Gf]*Wmass^2)/Zmass,
     gc18 -> 4*Sqrt[2]*Gf*Wmass^2,
     gc19 -> Lam*MX^2*UFOOrder,
     gc22[e1x2_, e1x3_, e2x2_, e2x3_, e3x1_, e3x2_, e3x3_] -> Lam*Conjugate[Cduu3[e1x2, e2x2, {{-F[4, {e1x2, e1x3}], 1}, {-F[3, {e2x2, e2x3}], 2}, {-S[31, {e3x1, e3x2, e3x3}], 3}}[[First[[{3, 1}]],1]][[2,1 + {}[[1]]]], {{-F[4, {e1x2, e1x3}], 1}, {-F[3, {e2x2, e2x3}], 2}, {-S[31, {e3x1, e3x2, e3x3}], 3}}[[First[[{3, 2}]],1]][[2,1 + {}[[1]]]]]]*Eps[e1x3, e2x3, e3x3],
     gc23 -> (4*Sqrt[2]*Gf*Wmass^3*Sqrt[-Wmass^2 + Zmass^2])/Zmass^2,
     gc26 -> (-4*Sqrt[2]*Gf*Wmass^4)/Zmass^2,
     gc27 -> (2*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(3*Zmass),
     gc28 -> (-4*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(3*Zmass),
     gc29 -> -(2^(3/4)*Sqrt[Gf]*Wmass),
     gc30[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Kq[e1x2, e2x2]),
     gc31[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Conjugate[Kq[e2x2, e1x2]]),
     gc32 -> -(2^(3/4)*Sqrt[Gf]*Wmass),
     gc33 -> (2^(1/4)*Sqrt[Gf]*(2*Wmass^2 + Zmass^2))/(3*Zmass),
     gc34 -> -((2^(1/4)*Sqrt[Gf]*(-2*Wmass^2 + Zmass^2))/Zmass),
     gc35 -> (2^(1/4)*Sqrt[Gf]*(-4*Wmass^2 + Zmass^2))/(3*Zmass),
     gc36 -> -(2^(1/4)*Sqrt[Gf]*Zmass),
     gc37 -> Lam^2/(2*Sqrt[2]*Gf),
     gc38 -> Lam^2/(2^(1/4)*Sqrt[Gf]),
     gc39 -> Lam^2,
     gc40[e1x2_, e3x2_, e2x2_, e4x2_] -> (Lam^2*(Cl4phi2n1[e1x2, e2x2, e3x2, e4x2] + Cl4phi2n1[e3x2, e4x2, e1x2, e2x2]))/(2*Sqrt[2]*Gf),
     gc41[e1x2_, e3x2_, e2x2_, e4x2_] -> (Lam^2*(Cl4phi2n1[e1x2, e2x2, e3x2, e4x2] + Cl4phi2n1[e3x2, e4x2, e1x2, e2x2]))/(2^(1/4)*Sqrt[Gf]),
     gc42[e1x2_, e3x2_, e2x2_, e4x2_] -> Lam^2*(Cl4phi2n1[e1x2, e2x2, e3x2, e4x2] + Cl4phi2n1[e3x2, e4x2, e1x2, e2x2]),
     gc43 -> Lam^2/(2*Sqrt[2]*Gf),
     gc44 -> Lam^2/(2^(1/4)*Sqrt[Gf]),
     gc45 -> Lam^2};

