(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMEFT",
  Authors -> "A. Dedes, J. Rosiek, M. Ryczkowski",
  Version -> "4.04",
  Date -> "01. 04. 2026",
  Emails -> "janusz.rosiek@fuw.edu.pl",
  URLs -> "URL: www.fuw.edu.pl/smeft"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {NP, 0}, {CP, 0}, {UFO, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "A",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "g",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mvdiag },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mldiag },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mudiag },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mddiag },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MG0,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MGP,
    Indices -> {} },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]A",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]Z",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "\[Eta]Wp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "\[Eta]Wm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]G",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

S[301] == {
    QuantumNumbers -> {-1/3*Q},
    Indices -> {Index[Generation], Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    PropagatorLabel -> xduq,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MX },

S[302] == {
    QuantumNumbers -> {-1/3*Q},
    Indices -> {Index[Generation], Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    PropagatorLabel -> xqqu,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MX },

S[303] == {
    QuantumNumbers -> {-1/3*Q},
    Indices -> {Index[SU2D], Index[SU2D], Index[Generation], Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    PropagatorLabel -> xqqq,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MX },

S[304] == {
    QuantumNumbers -> {-1/3*Q},
    Indices -> {Index[Generation], Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    PropagatorLabel -> xduu,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MX },

V[301] == {
    QuantumNumbers -> {0},
    Indices -> {Index[Generation], Index[Generation]},
    SelfConjugate -> False,
    PropagatorLabel -> xll,
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MX }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
mvdiag[ 1 ] := 0;
mvdiag[ 2 ] := 0;
mvdiag[ 3 ] := 0;
mldiag[ 1 ] := MLE;
mldiag[ 2 ] := MLM;
mldiag[ 3 ] := MLT;
mudiag[ 1, _ ] := MQU;
mudiag[ 1 ] := MQU;
mudiag[ 2, _ ] := MQC;
mudiag[ 2 ] := MQC;
mudiag[ 3, _ ] := MQT;
mudiag[ 3 ] := MQT;
mddiag[ 1, _ ] := MQD;
mddiag[ 1 ] := MQD;
mddiag[ 2, _ ] := MQS;
mddiag[ 2 ] := MQS;
mddiag[ 3, _ ] := MQB;
mddiag[ 3 ] := MQB;
MH[ ___ ] := MH;
MG0[ ___ ] := MG0;
MGP[ ___ ] := MGP;
MgZ[ ___ ] := MgZ;
MgW[ ___ ] := MgW;
MX[ ___ ] := MX;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ S[301, {__}] ] := TheLabel[S[301]];
TheLabel[ S[302, {__}] ] := TheLabel[S[302]];
TheLabel[ S[303, {__}] ] := TheLabel[S[303]];
TheLabel[ S[304, {__}] ] := TheLabel[S[304]];
TheLabel[ V[301, {__}] ] := TheLabel[V[301]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*2^(1/4)*Sqrt[Gf]*Hmass^2, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*Sqrt[2]*Gf*Hmass^2, 0}},

C[ S[1] , V[1] , V[1] ] == {{(-I)*gc3, 0}, {I*gc3, 0}, {0, 0}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{(-I)*gc4, 0}, {I*gc4, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[1] ] == {{(-I)*gc5, 0}, {I*gc5, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[1] ] == {{(-I)*gc6, 0}, {I*gc6, 0}},

C[ S[1] , V[1] , V[2] ] == {{(-I)*gc7, 0}, {I*gc7, 0}, {0, 0}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{(-I)*gc8, 0}, {I*gc8, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[2] ] == {{(-I)*gc9, 0}, {I*gc9, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[2] ] == {{(-I)*gc10, 0}, {I*gc10, 0}},

C[ S[1] , V[2] , V[2] ] == {{(2*I)*CB2phi4n1*gc11*Lam^2*(-Wmass^2 + Zmass^2), 0}, {(2*I)*CB2phi4n1*gc11*Lam^2*(Wmass^2 - Zmass^2), 0}, {I*gc11*Zmass^2*(2*Gf^2*Zmass^2 + CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2)), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{(6*I)*CB2phi4n1*gc12*Lam^2*(-Wmass^2 + Zmass^2), 0}, {(6*I)*CB2phi4n1*gc12*Lam^2*(Wmass^2 - Zmass^2), 0}, {I*gc12*Zmass^2*(2*Gf^2*Zmass^2 + CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2)), 0}},

C[ S[1] , S[1] , S[1] , V[2] , V[2] ] == {{(-I)*gc13, 0}, {I*gc13, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[2] , V[2] ] == {{(-I)*gc14, 0}, {I*gc14, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc15*SUNF[e1x2, e2x2, e3x2]), 0}, {gc15*SUNF[e1x2, e2x2, e3x2], 0}, {gc15*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc15*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc15*SUNF[e1x2, e2x2, e3x2]), 0}, {gc15*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc16*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc16*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc16*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc17*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc17*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc18*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc18*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc19L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc19R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc20L[e1x2, e2x2], 0}, {I*gc20R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc21L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc21R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc22, 0}, {I*gc22, 0}, {I*gc22, 0}, {(-I)*gc22, 0}, {(-I)*gc22, 0}, {I*gc22, 0}},

C[ S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc23, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc24, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc25, 0}, {(-I)*gc25, 0}, {(2*I)*gc25, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc26, 0}, {I*gc26, 0}, {I*gc26, 0}, {(-I)*gc26, 0}, {(-I)*gc26, 0}, {I*gc26, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc27, 0}, {(-I)*gc27, 0}, {(2*I)*gc27, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc28, 0}, {I*gc28, 0}, {I*gc28, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc29, 0}, {(-I)*gc29, 0}, {(2*I)*gc29, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc30*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc30*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc31*IndexDelta[e1x2, e2x2], 0}, {I*gc31*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc32*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc32*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc33*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc34[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc35[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc36*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc37L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc37R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc38L*IndexDelta[e1x2, e2x2], 0}, {I*gc38R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc39L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc39R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc40*IndexDelta[e1x2, e2x2], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc3 -> (-2*2^(1/4)*CB2phi4n1*Lam^2*Wmass^2)/(Gf^(3/2)*Zmass^2),
     gc4 -> (-6*Sqrt[2]*CB2phi4n1*Lam^2*Wmass^2)/(Gf*Zmass^2),
     gc5 -> (-12*2^(3/4)*CB2phi4n1*Lam^2*Wmass^2)/(Sqrt[Gf]*Zmass^2),
     gc6 -> (-24*CB2phi4n1*Lam^2*Wmass^2)/Zmass^2,
     gc7 -> (2*2^(1/4)*CB2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(Gf^(3/2)*Zmass^2),
     gc8 -> (6*Sqrt[2]*CB2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(Gf*Zmass^2),
     gc9 -> (12*2^(3/4)*CB2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(Sqrt[Gf]*Zmass^2),
     gc10 -> (24*CB2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/Zmass^2,
     gc11 -> 2^(1/4)/(Gf^(3/2)*Zmass^2),
     gc12 -> Sqrt[2]/(Gf*Zmass^2),
     gc13 -> (12*2^(3/4)*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/(Sqrt[Gf]*Zmass^2),
     gc14 -> (24*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Zmass^2,
     gc15 -> 2*Sqrt[aS]*Sqrt[Pi],
     gc16 -> -4*aS*Pi,
     gc17 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc18 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc19L[e1x2_, e2x2_] -> -(IndexSum[Conjugate[VDR[b1, e1x2]]*IndexSum[Conjugate[SMEFT$YD[a1, b1]]*VDL[a1, e2x2], {a1, 1, 3}], {b1, 1, 3}]/Sqrt[2]),
     gc19R[e1x2_, e2x2_] -> -(IndexSum[IndexSum[Conjugate[VDL[c1, e1x2]]*SMEFT$YD[c1, d1], {c1, 1, 3}]*VDR[d1, e2x2], {d1, 1, 3}]/Sqrt[2]),
     gc20L[e1x2_, e2x2_] -> -(IndexSum[Conjugate[VLR[b1, e1x2]]*IndexSum[Conjugate[SMEFT$YL[a1, b1]]*VLL[a1, e2x2], {a1, 1, 3}], {b1, 1, 3}]/Sqrt[2]),
     gc20R[e1x2_, e2x2_] -> -(IndexSum[IndexSum[Conjugate[VLL[c1, e1x2]]*SMEFT$YL[c1, d1], {c1, 1, 3}]*VLR[d1, e2x2], {d1, 1, 3}]/Sqrt[2]),
     gc21L[e1x2_, e2x2_] -> -(IndexSum[Conjugate[VUR[b1, e1x2]]*IndexSum[Conjugate[SMEFT$YU[a1, b1]]*VUL[a1, e2x2], {a1, 1, 3}], {b1, 1, 3}]/Sqrt[2]),
     gc21R[e1x2_, e2x2_] -> -(IndexSum[IndexSum[Conjugate[VUL[c1, e1x2]]*SMEFT$YU[c1, d1], {c1, 1, 3}]*VUR[d1, e2x2], {d1, 1, 3}]/Sqrt[2]),
     gc22 -> -((Wmass*Sqrt[-Wmass^2 + Zmass^2]*(4*Gf^2*Zmass - CB2phi4n1*Lam^2*Zmass + (4*CB2phi4n1*Lam^2*Wmass^2)/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/(2^(3/4)*Gf^(3/2)*Zmass^2)),
     gc23 -> 2*2^(1/4)*Sqrt[Gf]*Wmass^2,
     gc24 -> 2*Sqrt[2]*Gf*Wmass^2,
     gc25 -> (-2*Wmass^2*(-Wmass^2 + Zmass^2)*(2*Gf^2*Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4] + CB2phi4n1*Lam^2*(4*Wmass^2 - Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4])))/(Gf*Zmass^3*Sqrt[8*Zmass^2 + (4*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/(2*Gf^4)]),
     gc26 -> (-2*2^(1/4)*Wmass^2*(Gf^2*Zmass + (CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/(Gf^(3/2)*Zmass^2),
     gc27 -> 4*Sqrt[2]*Gf*Wmass^2,
     gc28 -> (Sqrt[2]*Wmass^3*Sqrt[-Wmass^2 + Zmass^2]*(4*Gf^2*Zmass + (CB2phi4n1*Lam^2*(8*Wmass^2 - Zmass*(4*Zmass + Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4])))/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/(Gf*Zmass^3),
     gc29 -> (-8*Sqrt[2]*Wmass^4*((Gf^2*Zmass)/2 + (CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/(Gf*Zmass^3),
     gc30 -> (Wmass*Sqrt[-Wmass^2 + Zmass^2]*(4*Gf^2*Zmass - CB2phi4n1*Lam^2*Zmass + (4*CB2phi4n1*Lam^2*Wmass^2)/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/(3*2^(3/4)*Gf^(3/2)*Zmass^2),
     gc31 -> (Wmass*Sqrt[-Wmass^2 + Zmass^2]*(4*Gf^2*Zmass - CB2phi4n1*Lam^2*Zmass + (4*CB2phi4n1*Lam^2*Wmass^2)/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/(2^(3/4)*Gf^(3/2)*Zmass^2),
     gc32 -> -1/3*(2^(1/4)*Wmass*Sqrt[-Wmass^2 + Zmass^2]*(4*Gf^2*Zmass - CB2phi4n1*Lam^2*Zmass + (4*CB2phi4n1*Lam^2*Wmass^2)/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/(Gf^(3/2)*Zmass^2),
     gc33 -> -(2^(3/4)*Sqrt[Gf]*Wmass),
     gc34[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Kq[e1x2, e2x2]),
     gc35[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Conjugate[Kq[e2x2, e1x2]]),
     gc36 -> -(2^(3/4)*Sqrt[Gf]*Wmass),
     gc37L -> (4*Gf^2*Zmass*(2*Wmass^2 + Zmass^2) + (CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2)*(8*Wmass^2 + Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4])/(6*2^(3/4)*Gf^(3/2)*Zmass^2),
     gc37R -> ((Wmass^2 - Zmass^2)*(4*Gf^2*Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4] + CB2phi4n1*Lam^2*(4*Wmass^2 - Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4])))/(3*2^(3/4)*Gf^(3/2)*Zmass^2*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]),
     gc38L -> -1/2*(4*Gf^2*Zmass*(-2*Wmass^2 + Zmass^2) + (CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2)*(-8*Wmass^2 + Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4])/(2^(3/4)*Gf^(3/2)*Zmass^2),
     gc38R -> ((Wmass^2 - Zmass^2)*(4*Gf^2*Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4] + CB2phi4n1*Lam^2*(4*Wmass^2 - Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4])))/(2^(3/4)*Gf^(3/2)*Zmass^2*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]),
     gc39L -> (4*Gf^2*Zmass*(-4*Wmass^2 + Zmass^2) + (CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2)*(-16*Wmass^2 + Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]))/Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4])/(6*2^(3/4)*Gf^(3/2)*Zmass^2),
     gc39R -> (2^(1/4)*(-Wmass^2 + Zmass^2)*(4*Gf^2*Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4] + CB2phi4n1*Lam^2*(4*Wmass^2 - Zmass*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4])))/(3*Gf^(3/2)*Zmass^2*Sqrt[16*Zmass^2 + (8*CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Gf^2 + (CB2phi4n1^2*Lam^4*(-Wmass^2 + Zmass^2))/Gf^4]),
     gc40 -> (-4*Gf^2*Zmass^2 - CB2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/(2*2^(3/4)*Gf^(3/2)*Zmass)};

