(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMEFT",
  Authors -> {"A. Dedes, J. Rosiek, M. Ryczkowski, K. Suxho, L. Trifyllis"},
  Version -> "3.02",
  Date -> "24. 04. 2023"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {NP, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "A",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "g",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mvdiag },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mldiag },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mudiag },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mddiag },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MG0,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MGP,
    Indices -> {} },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]A",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]Z",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "\[Eta]Wp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "\[Eta]Wm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]G",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
mvdiag[ 1 ] := 0;
mvdiag[ 2 ] := 0;
mvdiag[ 3 ] := 0;
mldiag[ 1 ] := MLE;
mldiag[ 2 ] := MLM;
mldiag[ 3 ] := MLT;
mudiag[ 1, _ ] := MQU;
mudiag[ 1 ] := MQU;
mudiag[ 2, _ ] := MQC;
mudiag[ 2 ] := MQC;
mudiag[ 3, _ ] := MQT;
mudiag[ 3 ] := MQT;
mddiag[ 1, _ ] := MQD;
mddiag[ 1 ] := MQD;
mddiag[ 2, _ ] := MQS;
mddiag[ 2 ] := MQS;
mddiag[ 3, _ ] := MQB;
mddiag[ 3 ] := MQB;
MH[ ___ ] := MH;
MG0[ ___ ] := MG0;
MGP[ ___ ] := MGP;
MgZ[ ___ ] := MgZ;
MgW[ ___ ] := MgW;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*2^(1/4)*Sqrt[Gf]*Hmass^2, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*Sqrt[2]*Gf*Hmass^2, 0}},

C[ S[1] , V[1] , V[1] ] == {{(-I)*gc3, 0}, {I*gc3, 0}, {0, 0}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{(-I)*gc4, 0}, {I*gc4, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[1] ] == {{(-I)*gc5, 0}, {I*gc5, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[1] ] == {{(-I)*gc6, 0}, {I*gc6, 0}},

C[ S[1] , V[3] , -V[3] ] == {{I*CW2phi4n1*gc7*Lam^2, 0}, {(-I)*CW2phi4n1*gc7*Lam^2, 0}, {I*gc7*Gf^2*Wmass^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{(3*I)*CW2phi4n1*gc8*Lam^2, 0}, {(-3*I)*CW2phi4n1*gc8*Lam^2, 0}, {I*gc8*Gf^2*Wmass^2, 0}},

C[ S[1] , S[1] , S[1] , V[3] , -V[3] ] == {{(-I)*gc9, 0}, {I*gc9, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[3] , -V[3] ] == {{(-I)*gc10, 0}, {I*gc10, 0}},

C[ S[1] , V[1] , V[2] ] == {{(-I)*gc11, 0}, {I*gc11, 0}, {0, 0}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{(-I)*gc12, 0}, {I*gc12, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[2] ] == {{(-I)*gc13, 0}, {I*gc13, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[2] ] == {{(-I)*gc14, 0}, {I*gc14, 0}},

C[ S[1] , V[2] , V[2] ] == {{I*CW2phi4n1*gc15*Lam^2*Wmass^2, 0}, {(-I)*CW2phi4n1*gc15*Lam^2*Wmass^2, 0}, {I*gc15*Gf^2*Zmass^4, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{(3*I)*CW2phi4n1*gc16*Lam^2*Wmass^2, 0}, {(-3*I)*CW2phi4n1*gc16*Lam^2*Wmass^2, 0}, {I*gc16*Gf^2*Zmass^4, 0}},

C[ S[1] , S[1] , S[1] , V[2] , V[2] ] == {{(-I)*gc17, 0}, {I*gc17, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[2] , V[2] ] == {{(-I)*gc18, 0}, {I*gc18, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc19*SUNF[e1x2, e2x2, e3x2]), 0}, {gc19*SUNF[e1x2, e2x2, e3x2], 0}, {gc19*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc19*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc19*SUNF[e1x2, e2x2, e3x2]), 0}, {gc19*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc20*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc20*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc20*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc21[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc21[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc22[e1x2, e2x2], 0}, {I*gc22[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc23[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc23[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc24, 0}, {I*gc24, 0}, {I*gc24, 0}, {(-I)*gc24, 0}, {(-I)*gc24, 0}, {I*gc24, 0}},

C[ S[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc25, 0}, {I*gc25, 0}, {I*gc25, 0}, {(-I)*gc25, 0}, {(-I)*gc25, 0}, {I*gc25, 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc26, 0}, {I*gc26, 0}, {I*gc26, 0}, {(-I)*gc26, 0}, {(-I)*gc26, 0}, {I*gc26, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc27, 0}, {I*gc27, 0}, {I*gc27, 0}, {(-I)*gc27, 0}, {(-I)*gc27, 0}, {I*gc27, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc28, 0}, {I*gc28, 0}, {I*gc28, 0}, {(-I)*gc28, 0}, {(-I)*gc28, 0}, {I*gc28, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc29, 0}, {(-I)*gc29, 0}, {(2*I)*gc29, 0}},

C[ S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc30, 0}, {(-I)*gc30, 0}, {(2*I)*gc30, 0}},

C[ S[1] , S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc31, 0}, {(-I)*gc31, 0}, {(2*I)*gc31, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc32, 0}, {(-I)*gc32, 0}, {(2*I)*gc32, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc33, 0}, {(-I)*gc33, 0}, {(2*I)*gc33, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc34, 0}, {I*gc34, 0}, {I*gc34, 0}, {(-I)*gc34, 0}, {(-I)*gc34, 0}, {I*gc34, 0}},

C[ S[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc35, 0}, {I*gc35, 0}, {I*gc35, 0}, {(-I)*gc35, 0}, {(-I)*gc35, 0}, {I*gc35, 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc36, 0}, {I*gc36, 0}, {I*gc36, 0}, {(-I)*gc36, 0}, {(-I)*gc36, 0}, {I*gc36, 0}},

C[ S[1] , S[1] , S[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc37, 0}, {I*gc37, 0}, {I*gc37, 0}, {(-I)*gc37, 0}, {(-I)*gc37, 0}, {I*gc37, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[3] , -V[3] , V[2] ] == {{(-I)*gc38, 0}, {I*gc38, 0}, {I*gc38, 0}, {(-I)*gc38, 0}, {(-I)*gc38, 0}, {I*gc38, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc39, 0}, {(-I)*gc39, 0}, {(2*I)*gc39, 0}},

C[ S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc40, 0}, {(-I)*gc40, 0}, {(2*I)*gc40, 0}},

C[ S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc41, 0}, {(-I)*gc41, 0}, {(2*I)*gc41, 0}},

C[ S[1] , S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc42, 0}, {(-I)*gc42, 0}, {(2*I)*gc42, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc43, 0}, {(-I)*gc43, 0}, {(2*I)*gc43, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc44, 0}, {I*gc44, 0}, {I*gc44, 0}},

C[ S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc45, 0}, {I*gc45, 0}, {I*gc45, 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc46, 0}, {I*gc46, 0}, {I*gc46, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc47, 0}, {I*gc47, 0}, {I*gc47, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc48, 0}, {I*gc48, 0}, {I*gc48, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc49, 0}, {(-I)*gc49, 0}, {(2*I)*gc49, 0}},

C[ S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc50, 0}, {(-I)*gc50, 0}, {(2*I)*gc50, 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc51, 0}, {(-I)*gc51, 0}, {(2*I)*gc51, 0}},

C[ S[1] , S[1] , S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc52, 0}, {(-I)*gc52, 0}, {(2*I)*gc52, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc53, 0}, {(-I)*gc53, 0}, {(2*I)*gc53, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc54*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc54*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc55*IndexDelta[e1x2, e2x2], 0}, {I*gc55*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc56*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc56*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc57*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc57*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc58*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc58*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc59[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc60[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc61[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc62[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc63L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc63R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc64L*IndexDelta[e1x2, e2x2], 0}, {I*gc64R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc65L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc65R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc66*IndexDelta[e1x2, e2x2], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc3 -> (2*2^(1/4)*CW2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/(Gf^(3/2)*Zmass^2),
     gc4 -> (6*Sqrt[2]*CW2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/(Gf*Zmass^2),
     gc5 -> (12*2^(3/4)*CW2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/(Sqrt[Gf]*Zmass^2),
     gc6 -> (24*CW2phi4n1*Lam^2*(Wmass^2 - Zmass^2))/Zmass^2,
     gc7 -> (2*2^(1/4))/Gf^(3/2),
     gc8 -> (2*Sqrt[2])/Gf,
     gc9 -> (-12*2^(3/4)*CW2phi4n1*Lam^2)/Sqrt[Gf],
     gc10 -> -24*CW2phi4n1*Lam^2,
     gc11 -> (-2*2^(1/4)*CW2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(Gf^(3/2)*Zmass^2),
     gc12 -> (-6*Sqrt[2]*CW2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(Gf*Zmass^2),
     gc13 -> (-12*2^(3/4)*CW2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(Sqrt[Gf]*Zmass^2),
     gc14 -> (-24*CW2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/Zmass^2,
     gc15 -> (2*2^(1/4))/(Gf^(3/2)*Zmass^2),
     gc16 -> (2*Sqrt[2])/(Gf*Zmass^2),
     gc17 -> (-12*2^(3/4)*CW2phi4n1*Lam^2*Wmass^2)/(Sqrt[Gf]*Zmass^2),
     gc18 -> (-24*CW2phi4n1*Lam^2*Wmass^2)/Zmass^2,
     gc19 -> 2*Sqrt[aS]*Sqrt[Pi],
     gc20 -> -4*aS*Pi,
     gc21[e1x2_, e2x2_] -> -(2^(1/4)*Sqrt[Gf]*fmd[e1x2, e2x2]),
     gc22[e1x2_, e2x2_] -> -(2^(1/4)*Sqrt[Gf]*fml[e1x2, e2x2]),
     gc23[e1x2_, e2x2_] -> -(2^(1/4)*Sqrt[Gf]*fmu[e1x2, e2x2]),
     gc24 -> (-2*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc25 -> (4*Sqrt[2]*CW2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(Gf*Zmass),
     gc26 -> (12*2^(3/4)*CW2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(Sqrt[Gf]*Zmass),
     gc27 -> (48*CW2phi4n1*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc28 -> (48*2^(1/4)*CW2phi4n1*Sqrt[Gf]*Lam^2*Wmass*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc29 -> (4*Sqrt[2]*Gf*Wmass^2*(Wmass^2 - Zmass^2))/Zmass^2,
     gc30 -> (8*2^(3/4)*CW2phi4n1*Lam^2*(-Wmass^4 + Wmass^2*Zmass^2))/(Sqrt[Gf]*Zmass^2),
     gc31 -> (-48*CW2phi4n1*Lam^2*Wmass^2*(Wmass^2 - Zmass^2))/Zmass^2,
     gc32 -> (-96*2^(1/4)*CW2phi4n1*Sqrt[Gf]*Lam^2*Wmass^2*(Wmass^2 - Zmass^2))/Zmass^2,
     gc33 -> (-96*Sqrt[2]*CW2phi4n1*Gf*Lam^2*Wmass^2*(Wmass^2 - Zmass^2))/Zmass^2,
     gc34 -> (-2*2^(1/4)*Sqrt[Gf]*Wmass^2)/Zmass,
     gc35 -> (4*Sqrt[2]*CW2phi4n1*Lam^2*Wmass^2)/(Gf*Zmass),
     gc36 -> (12*2^(3/4)*CW2phi4n1*Lam^2*Wmass^2)/(Sqrt[Gf]*Zmass),
     gc37 -> (48*CW2phi4n1*Lam^2*Wmass^2)/Zmass,
     gc38 -> (48*2^(1/4)*CW2phi4n1*Sqrt[Gf]*Lam^2*Wmass^2)/Zmass,
     gc39 -> 4*Sqrt[2]*Gf*Wmass^2,
     gc40 -> (-8*2^(3/4)*CW2phi4n1*Lam^2*Wmass^2)/Sqrt[Gf],
     gc41 -> -48*CW2phi4n1*Lam^2*Wmass^2,
     gc42 -> -96*2^(1/4)*CW2phi4n1*Sqrt[Gf]*Lam^2*Wmass^2,
     gc43 -> -96*Sqrt[2]*CW2phi4n1*Gf*Lam^2*Wmass^2,
     gc44 -> (4*Sqrt[2]*Gf*Wmass^3*Sqrt[-Wmass^2 + Zmass^2])/Zmass^2,
     gc45 -> (-8*2^(3/4)*CW2phi4n1*Lam^2*Wmass^3*Sqrt[-Wmass^2 + Zmass^2])/(Sqrt[Gf]*Zmass^2),
     gc46 -> (-48*CW2phi4n1*Lam^2*Wmass^3*Sqrt[-Wmass^2 + Zmass^2])/Zmass^2,
     gc47 -> (-96*2^(1/4)*CW2phi4n1*Sqrt[Gf]*Lam^2*Wmass^3*Sqrt[-Wmass^2 + Zmass^2])/Zmass^2,
     gc48 -> (-96*Sqrt[2]*CW2phi4n1*Gf*Lam^2*Wmass^3*Sqrt[-Wmass^2 + Zmass^2])/Zmass^2,
     gc49 -> (-4*Sqrt[2]*Gf*Wmass^4)/Zmass^2,
     gc50 -> (8*2^(3/4)*CW2phi4n1*Lam^2*Wmass^4)/(Sqrt[Gf]*Zmass^2),
     gc51 -> (48*CW2phi4n1*Lam^2*Wmass^4)/Zmass^2,
     gc52 -> (96*2^(1/4)*CW2phi4n1*Sqrt[Gf]*Lam^2*Wmass^4)/Zmass^2,
     gc53 -> (96*Sqrt[2]*CW2phi4n1*Gf*Lam^2*Wmass^4)/Zmass^2,
     gc54 -> (2*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(3*Zmass),
     gc55 -> (2*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc56 -> (-4*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(3*Zmass),
     gc57 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc58 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc59[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Conjugate[Ul[e2x2, e1x2]]),
     gc60[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Kq[e1x2, e2x2]),
     gc61[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Conjugate[Kq[e2x2, e1x2]]),
     gc62[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Ul[e1x2, e2x2]),
     gc63L -> (2^(1/4)*Sqrt[Gf]*(2*Wmass^2 + Zmass^2))/(3*Zmass),
     gc63R -> (2*2^(1/4)*Sqrt[Gf]*(Wmass^2 - Zmass^2))/(3*Zmass),
     gc64L -> -((2^(1/4)*Sqrt[Gf]*(-2*Wmass^2 + Zmass^2))/Zmass),
     gc64R -> (2*2^(1/4)*Sqrt[Gf]*(Wmass^2 - Zmass^2))/Zmass,
     gc65L -> (2^(1/4)*Sqrt[Gf]*(-4*Wmass^2 + Zmass^2))/(3*Zmass),
     gc65R -> (4*2^(1/4)*Sqrt[Gf]*(-Wmass^2 + Zmass^2))/(3*Zmass),
     gc66 -> -(2^(1/4)*Sqrt[Gf]*Zmass)};

