(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMEFT",
  Authors -> {"A. Dedes, J. Rosiek, M. Ryczkowski, K. Suxho, L. Trifyllis"},
  Version -> "3.02",
  Date -> "24. 04. 2023"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {NP, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "A",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "g",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mvdiag },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mldiag },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mudiag },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mddiag },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MG0,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MGP,
    Indices -> {} },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]A",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]Z",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "\[Eta]Wp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "\[Eta]Wm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]G",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
mvdiag[ 1 ] := 0;
mvdiag[ 2 ] := 0;
mvdiag[ 3 ] := 0;
mldiag[ 1 ] := MLE;
mldiag[ 2 ] := MLM;
mldiag[ 3 ] := MLT;
mudiag[ 1, _ ] := MQU;
mudiag[ 1 ] := MQU;
mudiag[ 2, _ ] := MQC;
mudiag[ 2 ] := MQC;
mudiag[ 3, _ ] := MQT;
mudiag[ 3 ] := MQT;
mddiag[ 1, _ ] := MQD;
mddiag[ 1 ] := MQD;
mddiag[ 2, _ ] := MQS;
mddiag[ 2 ] := MQS;
mddiag[ 3, _ ] := MQB;
mddiag[ 3 ] := MQB;
MH[ ___ ] := MH;
MG0[ ___ ] := MG0;
MGP[ ___ ] := MGP;
MgZ[ ___ ] := MgZ;
MgW[ ___ ] := MgW;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] ] == {{(-3*I)*2^(1/4)*Sqrt[Gf]*Hmass^2, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-3*I)*Sqrt[2]*Gf*Hmass^2, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc3*SUNF[e1x2, e2x2, e3x2]), 0}, {gc3*SUNF[e1x2, e2x2, e3x2], 0}, {gc3*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc3*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc3*SUNF[e1x2, e2x2, e3x2]), 0}, {gc3*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc4*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc4*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc4*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc5[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc5[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc6[e1x2, e2x2], 0}, {I*gc6[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc7[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc7[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ V[1] , V[3] , -V[3] ] == {{-(gc8*((8*I)*Gf^(3/2) + 2^(1/4)*CWphi4D2n1*Lam^2*Wmass)), 0}, {(8*I)*gc8*Gf^(3/2), 0}, {gc8*((8*I)*Gf^(3/2) + 2^(1/4)*CWphi4D2n1*Lam^2*Wmass), 0}, {(-8*I)*gc8*Gf^(3/2), 0}, {(-8*I)*gc8*Gf^(3/2), 0}, {(8*I)*gc8*Gf^(3/2), 0}},

C[ S[1] , V[3] , -V[3] ] == {{-(CWphi4D2n1*gc9*Lam^2), 0}, {-(CWphi4D2n1*gc9*Lam^2), 0}, {(4*I)*2^(3/4)*gc9*Gf^(3/2)*Wmass, 0}, {CWphi4D2n1*gc9*Lam^2, 0}, {CWphi4D2n1*gc9*Lam^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{-3*CWphi4D2n1*gc10*Lam^2, 0}, {-3*CWphi4D2n1*gc10*Lam^2, 0}, {-3*CWphi4D2n1*gc10*Lam^2, 0}, {-3*CWphi4D2n1*gc10*Lam^2, 0}, {(4*I)*2^(3/4)*gc10*Gf^(3/2)*Wmass, 0}, {3*CWphi4D2n1*gc10*Lam^2, 0}, {3*CWphi4D2n1*gc10*Lam^2, 0}, {3*CWphi4D2n1*gc10*Lam^2, 0}, {3*CWphi4D2n1*gc10*Lam^2, 0}},

C[ S[1] , S[1] , S[1] , V[3] , -V[3] ] == {{-gc11, 0}, {-gc11, 0}, {-gc11, 0}, {-gc11, 0}, {-gc11, 0}, {-gc11, 0}, {gc11, 0}, {gc11, 0}, {gc11, 0}, {gc11, 0}, {gc11, 0}, {gc11, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[3] , -V[3] ] == {{-gc12, 0}, {-gc12, 0}, {-gc12, 0}, {-gc12, 0}, {-gc12, 0}, {-gc12, 0}, {-gc12, 0}, {-gc12, 0}, {gc12, 0}, {gc12, 0}, {gc12, 0}, {gc12, 0}, {gc12, 0}, {gc12, 0}, {gc12, 0}, {gc12, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc13, 0}, {(-I)*gc13, 0}, {(2*I)*gc13, 0}},

C[ S[1] , V[1] , V[3] , -V[3] ] == {{gc14, 0}, {-2*gc14, 0}, {-gc14, 0}, {2*gc14, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] ] == {{gc15, 0}, {gc15, 0}, {-2*gc15, 0}, {-gc15, 0}, {-gc15, 0}, {2*gc15, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[3] , -V[3] ] == {{gc16, 0}, {gc16, 0}, {gc16, 0}, {-2*gc16, 0}, {-gc16, 0}, {-gc16, 0}, {-gc16, 0}, {2*gc16, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[3] , -V[3] ] == {{gc17, 0}, {gc17, 0}, {gc17, 0}, {gc17, 0}, {-2*gc17, 0}, {-gc17, 0}, {-gc17, 0}, {-gc17, 0}, {-gc17, 0}, {2*gc17, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},

C[ V[3] , -V[3] , V[2] ] == {{-(gc18*((8*I)*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2)), 0}, {gc18*((8*I)*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2), 0}, {gc18*((8*I)*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2), 0}, {-(gc18*Wmass*((8*I)*Gf^(3/2) + 2^(1/4)*CWphi4D2n1*Lam^2*Wmass)), 0}, {-(gc18*((8*I)*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2)), 0}, {gc18*Wmass*((8*I)*Gf^(3/2) + 2^(1/4)*CWphi4D2n1*Lam^2*Wmass), 0}},

C[ S[1] , V[3] , -V[3] , V[2] ] == {{0, 0}, {-2*gc19*Zmass^2, 0}, {gc19*(Wmass - Zmass)*(Wmass + Zmass), 0}, {2*gc19*Zmass^2, 0}, {2*gc19*Zmass^2, 0}, {-2*gc19*Wmass^2, 0}, {-(gc19*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-2*gc19*Zmass^2, 0}, {2*gc19*Wmass^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {-2*gc20*Zmass^2, 0}, {gc20*(Wmass - Zmass)*(Wmass + Zmass), 0}, {gc20*(Wmass - Zmass)*(Wmass + Zmass), 0}, {2*gc20*Zmass^2, 0}, {2*gc20*Zmass^2, 0}, {-2*gc20*Wmass^2, 0}, {-(gc20*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-(gc20*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-2*gc20*Zmass^2, 0}, {2*gc20*Wmass^2, 0}},

C[ S[1] , S[1] , S[1] , V[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {-2*gc21*Zmass^2, 0}, {gc21*(Wmass - Zmass)*(Wmass + Zmass), 0}, {gc21*(Wmass - Zmass)*(Wmass + Zmass), 0}, {gc21*(Wmass - Zmass)*(Wmass + Zmass), 0}, {2*gc21*Zmass^2, 0}, {2*gc21*Zmass^2, 0}, {-2*gc21*Wmass^2, 0}, {-(gc21*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-(gc21*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-(gc21*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-2*gc21*Zmass^2, 0}, {2*gc21*Wmass^2, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {-2*gc22*Zmass^2, 0}, {gc22*(Wmass - Zmass)*(Wmass + Zmass), 0}, {gc22*(Wmass - Zmass)*(Wmass + Zmass), 0}, {gc22*(Wmass - Zmass)*(Wmass + Zmass), 0}, {gc22*(Wmass - Zmass)*(Wmass + Zmass), 0}, {2*gc22*Zmass^2, 0}, {2*gc22*Zmass^2, 0}, {-2*gc22*Wmass^2, 0}, {-(gc22*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-(gc22*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-(gc22*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-(gc22*(Wmass - Zmass)*(Wmass + Zmass)), 0}, {-2*gc22*Zmass^2, 0}, {2*gc22*Wmass^2, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{gc23*((-2*I)*2^(3/4)*Gf^(3/2) - CWphi4D2n1*Lam^2*Wmass), 0}, {gc23*((-2*I)*2^(3/4)*Gf^(3/2) - CWphi4D2n1*Lam^2*Wmass), 0}, {2*gc23*((2*I)*2^(3/4)*Gf^(3/2) + CWphi4D2n1*Lam^2*Wmass), 0}},

C[ S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{-gc24, 0}, {-gc24, 0}, {2*gc24, 0}},

C[ S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{-gc25, 0}, {-gc25, 0}, {2*gc25, 0}},

C[ S[1] , S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{-gc26, 0}, {-gc26, 0}, {2*gc26, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{-gc27, 0}, {-gc27, 0}, {2*gc27, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*gc28*((8*I)*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2))/(8*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2), 0}, {(gc28*((8*I)*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2))/(8*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2), 0}, {(gc28*((8*I)*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2))/(8*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2), 0}},

C[ S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{-2*gc29, 0}, {gc29, 0}, {gc29, 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{-2*gc30, 0}, {gc30, 0}, {gc30, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{-2*gc31, 0}, {gc31, 0}, {gc31, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{-2*gc32, 0}, {gc32, 0}, {gc32, 0}},

C[ S[1] , V[2] , V[2] ] == {{-(CWphi4D2n1*gc33*Lam^2*Wmass), 0}, {-(CWphi4D2n1*gc33*Lam^2*Wmass), 0}, {(4*I)*2^(3/4)*gc33*Gf^(3/2)*Zmass^2, 0}, {CWphi4D2n1*gc33*Lam^2*Wmass, 0}, {CWphi4D2n1*gc33*Lam^2*Wmass, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{-3*CWphi4D2n1*gc34*Lam^2*Wmass, 0}, {-3*CWphi4D2n1*gc34*Lam^2*Wmass, 0}, {-3*CWphi4D2n1*gc34*Lam^2*Wmass, 0}, {-3*CWphi4D2n1*gc34*Lam^2*Wmass, 0}, {(4*I)*2^(3/4)*gc34*Gf^(3/2)*Zmass^2, 0}, {3*CWphi4D2n1*gc34*Lam^2*Wmass, 0}, {3*CWphi4D2n1*gc34*Lam^2*Wmass, 0}, {3*CWphi4D2n1*gc34*Lam^2*Wmass, 0}, {3*CWphi4D2n1*gc34*Lam^2*Wmass, 0}},

C[ S[1] , V[1] , V[2] ] == {{-gc35, 0}, {0, 0}, {0, 0}, {gc35, 0}, {0, 0}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{-gc36, 0}, {-gc36, 0}, {0, 0}, {0, 0}, {0, 0}, {gc36, 0}, {0, 0}, {gc36, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , V[1] , V[2] ] == {{-gc37, 0}, {-gc37, 0}, {-gc37, 0}, {0, 0}, {0, 0}, {0, 0}, {gc37, 0}, {0, 0}, {gc37, 0}, {0, 0}, {gc37, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[1] , V[2] ] == {{-gc38, 0}, {-gc38, 0}, {-gc38, 0}, {-gc38, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {gc38, 0}, {0, 0}, {gc38, 0}, {0, 0}, {gc38, 0}, {0, 0}, {gc38, 0}, {0, 0}},

C[ S[1] , S[1] , S[1] , V[2] , V[2] ] == {{-gc39, 0}, {-gc39, 0}, {-gc39, 0}, {-gc39, 0}, {-gc39, 0}, {-gc39, 0}, {gc39, 0}, {gc39, 0}, {gc39, 0}, {gc39, 0}, {gc39, 0}, {gc39, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[2] , V[2] ] == {{-gc40, 0}, {-gc40, 0}, {-gc40, 0}, {-gc40, 0}, {-gc40, 0}, {-gc40, 0}, {-gc40, 0}, {-gc40, 0}, {gc40, 0}, {gc40, 0}, {gc40, 0}, {gc40, 0}, {gc40, 0}, {gc40, 0}, {gc40, 0}, {gc40, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{gc41*((-2*I)*2^(3/4)*Gf^(3/2)*Wmass - CWphi4D2n1*Lam^2*Zmass^2), 0}, {gc41*((-2*I)*2^(3/4)*Gf^(3/2)*Wmass - CWphi4D2n1*Lam^2*Zmass^2), 0}, {2*gc41*((2*I)*2^(3/4)*Gf^(3/2)*Wmass + CWphi4D2n1*Lam^2*Zmass^2), 0}},

C[ S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{-gc42, 0}, {-gc42, 0}, {2*gc42, 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{-gc43, 0}, {-gc43, 0}, {2*gc43, 0}},

C[ S[1] , S[1] , S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{-gc44, 0}, {-gc44, 0}, {2*gc44, 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{-gc45, 0}, {-gc45, 0}, {2*gc45, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc46*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc46*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc47*IndexDelta[e1x2, e2x2], 0}, {I*gc47*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc48*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc48*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc49*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc49*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc50*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc50*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc51[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc52[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc53[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc54[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc55L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc55R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc56L*IndexDelta[e1x2, e2x2], 0}, {I*gc56R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc57L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc57R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc58*IndexDelta[e1x2, e2x2], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc3 -> 2*Sqrt[aS]*Sqrt[Pi],
     gc4 -> -4*aS*Pi,
     gc5[e1x2_, e2x2_] -> -(2^(1/4)*Sqrt[Gf]*fmd[e1x2, e2x2]),
     gc6[e1x2_, e2x2_] -> -(2^(1/4)*Sqrt[Gf]*fml[e1x2, e2x2]),
     gc7[e1x2_, e2x2_] -> -(2^(1/4)*Sqrt[Gf]*fmu[e1x2, e2x2]),
     gc8 -> -1/2*(Wmass*Sqrt[-Wmass^2 + Zmass^2])/(2^(3/4)*Gf*Zmass),
     gc9 -> Wmass/(2*Sqrt[2]*Gf),
     gc10 -> Wmass/(2*2^(1/4)*Sqrt[Gf]),
     gc11 -> 3*CWphi4D2n1*Lam^2*Wmass,
     gc12 -> 3*2^(1/4)*CWphi4D2n1*Sqrt[Gf]*Lam^2*Wmass,
     gc13 -> (4*Sqrt[2]*Gf*Wmass^2*(Wmass^2 - Zmass^2))/Zmass^2,
     gc14 -> -((CWphi4D2n1*Lam^2*Wmass^2*Sqrt[-Wmass^2 + Zmass^2])/(2^(1/4)*Sqrt[Gf]*Zmass)),
     gc15 -> (-3*CWphi4D2n1*Lam^2*Wmass^2*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc16 -> (-6*2^(1/4)*CWphi4D2n1*Sqrt[Gf]*Lam^2*Wmass^2*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc17 -> (-6*Sqrt[2]*CWphi4D2n1*Gf*Lam^2*Wmass^2*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc18 -> -1/2*Wmass/(2^(3/4)*Gf*Zmass),
     gc19 -> -((CWphi4D2n1*Lam^2*Wmass)/(2^(1/4)*Sqrt[Gf]*Zmass)),
     gc20 -> (-3*CWphi4D2n1*Lam^2*Wmass)/Zmass,
     gc21 -> (-6*2^(1/4)*CWphi4D2n1*Sqrt[Gf]*Lam^2*Wmass)/Zmass,
     gc22 -> (-6*Sqrt[2]*CWphi4D2n1*Gf*Lam^2*Wmass)/Zmass,
     gc23 -> (2^(3/4)*Wmass^2)/Sqrt[Gf],
     gc24 -> 8*CWphi4D2n1*Lam^2*Wmass^3,
     gc25 -> 24*2^(1/4)*CWphi4D2n1*Sqrt[Gf]*Lam^2*Wmass^3,
     gc26 -> 48*Sqrt[2]*CWphi4D2n1*Gf*Lam^2*Wmass^3,
     gc27 -> 48*2^(3/4)*CWphi4D2n1*Gf^(3/2)*Lam^2*Wmass^3,
     gc28 -> (Wmass^2*Sqrt[-Wmass^2 + Zmass^2]*(8*Gf^(3/2)*Wmass + 2^(1/4)*CWphi4D2n1*Lam^2*Zmass^2))/(Sqrt[2]*Sqrt[Gf]*Zmass^2),
     gc29 -> 4*CWphi4D2n1*Lam^2*Wmass^2*Sqrt[-Wmass^2 + Zmass^2],
     gc30 -> 12*2^(1/4)*CWphi4D2n1*Sqrt[Gf]*Lam^2*Wmass^2*Sqrt[-Wmass^2 + Zmass^2],
     gc31 -> 24*Sqrt[2]*CWphi4D2n1*Gf*Lam^2*Wmass^2*Sqrt[-Wmass^2 + Zmass^2],
     gc32 -> 24*2^(3/4)*CWphi4D2n1*Gf^(3/2)*Lam^2*Wmass^2*Sqrt[-Wmass^2 + Zmass^2],
     gc33 -> 1/(2*Sqrt[2]*Gf),
     gc34 -> 1/(2*2^(1/4)*Sqrt[Gf]),
     gc35 -> (CWphi4D2n1*Lam^2*Sqrt[-Wmass^2 + Zmass^2])/(2*Sqrt[2]*Gf),
     gc36 -> (3*CWphi4D2n1*Lam^2*Sqrt[-Wmass^2 + Zmass^2])/(2*2^(1/4)*Sqrt[Gf]),
     gc37 -> 3*CWphi4D2n1*Lam^2*Sqrt[-Wmass^2 + Zmass^2],
     gc38 -> 3*2^(1/4)*CWphi4D2n1*Sqrt[Gf]*Lam^2*Sqrt[-Wmass^2 + Zmass^2],
     gc39 -> 3*CWphi4D2n1*Lam^2*Wmass,
     gc40 -> 3*2^(1/4)*CWphi4D2n1*Sqrt[Gf]*Lam^2*Wmass,
     gc41 -> -((2^(3/4)*Wmass^3)/(Sqrt[Gf]*Zmass^2)),
     gc42 -> -8*CWphi4D2n1*Lam^2*Wmass^3,
     gc43 -> -24*2^(1/4)*CWphi4D2n1*Sqrt[Gf]*Lam^2*Wmass^3,
     gc44 -> -48*Sqrt[2]*CWphi4D2n1*Gf*Lam^2*Wmass^3,
     gc45 -> -48*2^(3/4)*CWphi4D2n1*Gf^(3/2)*Lam^2*Wmass^3,
     gc46 -> (2*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(3*Zmass),
     gc47 -> (2*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/Zmass,
     gc48 -> (-4*2^(1/4)*Sqrt[Gf]*Wmass*Sqrt[-Wmass^2 + Zmass^2])/(3*Zmass),
     gc49 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc50 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc51[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Conjugate[Ul[e2x2, e1x2]]),
     gc52[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Kq[e1x2, e2x2]),
     gc53[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Conjugate[Kq[e2x2, e1x2]]),
     gc54[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Ul[e1x2, e2x2]),
     gc55L -> (2^(1/4)*Sqrt[Gf]*(2*Wmass^2 + Zmass^2))/(3*Zmass),
     gc55R -> (2*2^(1/4)*Sqrt[Gf]*(Wmass^2 - Zmass^2))/(3*Zmass),
     gc56L -> -((2^(1/4)*Sqrt[Gf]*(-2*Wmass^2 + Zmass^2))/Zmass),
     gc56R -> (2*2^(1/4)*Sqrt[Gf]*(Wmass^2 - Zmass^2))/Zmass,
     gc57L -> (2^(1/4)*Sqrt[Gf]*(-4*Wmass^2 + Zmass^2))/(3*Zmass),
     gc57R -> (4*2^(1/4)*Sqrt[Gf]*(-Wmass^2 + Zmass^2))/(3*Zmass),
     gc58 -> -(2^(1/4)*Sqrt[Gf]*Zmass)};

