(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMEFT",
  Authors -> {"A. Dedes, J. Rosiek, M. Ryczkowski, K. Suxho, L. Trifyllis"},
  Version -> "3.02",
  Date -> "24. 04. 2023"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {NP, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "A",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "g",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mvdiag },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mldiag },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mudiag },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mddiag },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MG0,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MGP,
    Indices -> {} },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]A",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]Z",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "\[Eta]Wp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "\[Eta]Wm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]G",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
mvdiag[ 1 ] := 0;
mvdiag[ 2 ] := 0;
mvdiag[ 3 ] := 0;
mldiag[ 1 ] := MLE;
mldiag[ 2 ] := MLM;
mldiag[ 3 ] := MLT;
mudiag[ 1, _ ] := MQU;
mudiag[ 1 ] := MQU;
mudiag[ 2, _ ] := MQC;
mudiag[ 2 ] := MQC;
mudiag[ 3, _ ] := MQT;
mudiag[ 3 ] := MQT;
mddiag[ 1, _ ] := MQD;
mddiag[ 1 ] := MQD;
mddiag[ 2, _ ] := MQS;
mddiag[ 2 ] := MQS;
mddiag[ 3, _ ] := MQB;
mddiag[ 3 ] := MQB;
MH[ ___ ] := MH;
MG0[ ___ ] := MG0;
MGP[ ___ ] := MGP;
MgZ[ ___ ] := MgZ;
MgW[ ___ ] := MgW;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] ] == {{(3*I)*gc1*(64*Gf^3*Hmass^2 + 8*Sqrt[2]*(4*CphiBox - CphiD)*Gf^2*Hmass^2*Lam + 24*Sqrt[2]*Cphi*(-4*CphiBox + CphiD)*Lam^2 + Gf*Lam*(-64*Cphi + 3*(-4*CphiBox + CphiD)^2*Hmass^2*Lam)), 0}, {(24*I)*CphiBox*gc1*Gf*Lam*(4*Sqrt[2]*Gf + 12*CphiBox*Lam - 3*CphiD*Lam), 0}, {(8*I)*(2*CphiBox + CphiD)*gc1*Gf*Lam*(4*Sqrt[2]*Gf + 12*CphiBox*Lam - 3*CphiD*Lam), 0}, {(8*I)*(2*CphiBox + CphiD)*gc1*Gf*Lam*(4*Sqrt[2]*Gf + 12*CphiBox*Lam - 3*CphiD*Lam), 0}, {(24*I)*CphiBox*gc1*Gf*Lam*(4*Sqrt[2]*Gf + 12*CphiBox*Lam - 3*CphiD*Lam), 0}, {(8*I)*(2*CphiBox + CphiD)*gc1*Gf*Lam*(4*Sqrt[2]*Gf + 12*CphiBox*Lam - 3*CphiD*Lam), 0}, {(24*I)*CphiBox*gc1*Gf*Lam*(4*Sqrt[2]*Gf + 12*CphiBox*Lam - 3*CphiD*Lam), 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(3*I)*gc2*(8*Sqrt[2]*Gf^3*Hmass^2 + 4*(4*CphiBox - CphiD)*Gf^2*Hmass^2*Lam + 48*Cphi*(-4*CphiBox + CphiD)*Lam^2 + Sqrt[2]*Gf*Lam*(-48*Cphi + (-4*CphiBox + CphiD)^2*Hmass^2*Lam)), 0}, {(12*I)*CphiBox*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}, {(4*I)*(2*CphiBox + CphiD)*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}, {(4*I)*(2*CphiBox + CphiD)*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}, {(4*I)*(2*CphiBox + CphiD)*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}, {(12*I)*CphiBox*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}, {(4*I)*(2*CphiBox + CphiD)*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}, {(4*I)*(2*CphiBox + CphiD)*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}, {(12*I)*CphiBox*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}, {(4*I)*(2*CphiBox + CphiD)*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}, {(12*I)*CphiBox*gc2*Gf*Lam*(2*Gf + Sqrt[2]*(4*CphiBox - CphiD)*Lam), 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] ] == {{(((45*I)/2)*Cphi*Lam*(4*Sqrt[2]*Gf + 20*CphiBox*Lam - 5*CphiD*Lam))/(2^(3/4)*Gf^(3/2)), 0}},

C[ S[1] , S[1] , S[1] , S[1] , S[1] , S[1] ] == {{(((45*I)/2)*Cphi*Lam*(4*Gf + 3*Sqrt[2]*(4*CphiBox - CphiD)*Lam))/Gf, 0}},

C[ S[1] , V[1] , V[1] ] == {{(-I)*gc5, 0}, {I*gc5, 0}, {0, 0}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{(-I)*gc6, 0}, {I*gc6, 0}, {0, 0}},

C[ S[1] , V[3] , -V[3] ] == {{(16*I)*CphiW*gc7*Lam*(4*Sqrt[2]*Gf + (4*CphiBox - CphiD + 8*CphiW)*Lam), 0}, {(-16*I)*CphiW*gc7*Lam*(4*Sqrt[2]*Gf + (4*CphiBox - CphiD + 8*CphiW)*Lam), 0}, {I*gc7*(64*Gf^2 + 8*Sqrt[2]*(4*CphiBox - CphiD)*Gf*Lam + 3*(-4*CphiBox + CphiD)^2*Lam^2)*Wmass^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{(4*I)*CphiW*gc8*Lam*(4*Gf + Sqrt[2]*(4*CphiBox - CphiD + 4*CphiW)*Lam), 0}, {(-4*I)*CphiW*gc8*Lam*(4*Gf + Sqrt[2]*(4*CphiBox - CphiD + 4*CphiW)*Lam), 0}, {I*gc8*(8*Sqrt[2]*Gf^2 + 4*(4*CphiBox - CphiD)*Gf*Lam + Sqrt[2]*(-4*CphiBox + CphiD)^2*Lam^2)*Wmass^2, 0}},

C[ S[1] , V[1] , V[2] ] == {{(-I)*gc9, 0}, {I*gc9, 0}, {0, 0}},

C[ S[1] , S[1] , V[1] , V[2] ] == {{(-I)*gc10, 0}, {I*gc10, 0}, {0, 0}},

C[ S[1] , V[2] , V[2] ] == {{(-16*I)*gc11*Lam*(-4*CphiWB^2*Lam*(-Wmass^2 + Zmass^2)^(3/2) + CphiWB*Wmass*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiBox*Wmass^2 + CphiD*Wmass^2 + 12*CphiW*Wmass^2 - 4*CphiBox*Zmass^2 - 12*CphiW*Zmass^2 + 4*CphiB*(Wmass^2 - Zmass^2))) + Sqrt[-Wmass^2 + Zmass^2]*(-(CphiW*(4*Sqrt[2]*Gf + (4*CphiBox + CphiD + 8*CphiW)*Lam)*Wmass^2) + 8*CphiB^2*Lam*(Wmass^2 - Zmass^2) + CphiB*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + 4*CphiBox*Lam*(Wmass^2 - Zmass^2) + CphiD*Lam*(Wmass^2 + Zmass^2)))), 0}, {(16*I)*gc11*Lam*(-4*CphiWB^2*Lam*(-Wmass^2 + Zmass^2)^(3/2) + CphiWB*Wmass*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiBox*Wmass^2 + CphiD*Wmass^2 + 12*CphiW*Wmass^2 - 4*CphiBox*Zmass^2 - 12*CphiW*Zmass^2 + 4*CphiB*(Wmass^2 - Zmass^2))) + Sqrt[-Wmass^2 + Zmass^2]*(-(CphiW*(4*Sqrt[2]*Gf + (4*CphiBox + CphiD + 8*CphiW)*Lam)*Wmass^2) + 8*CphiB^2*Lam*(Wmass^2 - Zmass^2) + CphiB*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + 4*CphiBox*Lam*(Wmass^2 - Zmass^2) + CphiD*Lam*(Wmass^2 + Zmass^2)))), 0}, {I*gc11*(64*Gf^2 + 8*Sqrt[2]*(4*CphiBox + CphiD)*Gf*Lam + (48*CphiBox^2 - 8*CphiBox*CphiD - 9*CphiD^2)*Lam^2)*Zmass^4*Sqrt[-Wmass^2 + Zmass^2], 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{(2*I)*gc12*Lam*(4*Sqrt[2]*CphiWB^2*Lam*(-Wmass^2 + Zmass^2)^(3/2) - CphiWB*Wmass*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(8*CphiBox*Wmass^2 + 12*CphiW*Wmass^2 - 8*CphiBox*Zmass^2 + CphiD*Zmass^2 - 12*CphiW*Zmass^2 + 4*CphiB*(Wmass^2 - Zmass^2))) + 2*Sqrt[-Wmass^2 + Zmass^2]*(4*CphiW*(Gf + Sqrt[2]*(CphiBox + CphiW)*Lam)*Wmass^2 + 4*Sqrt[2]*CphiB^2*Lam*(-Wmass^2 + Zmass^2) - CphiB*(4*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(4*CphiBox*Wmass^2 - 4*CphiBox*Zmass^2 + CphiD*Zmass^2)))), 0}, {(2*I)*gc12*Lam*(-4*Sqrt[2]*CphiWB^2*Lam*(-Wmass^2 + Zmass^2)^(3/2) + CphiWB*Wmass*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(8*CphiBox*Wmass^2 + 12*CphiW*Wmass^2 - 8*CphiBox*Zmass^2 + CphiD*Zmass^2 - 12*CphiW*Zmass^2 + 4*CphiB*(Wmass^2 - Zmass^2))) + 2*Sqrt[-Wmass^2 + Zmass^2]*(-4*CphiW*(Gf + Sqrt[2]*(CphiBox + CphiW)*Lam)*Wmass^2 + 4*Sqrt[2]*CphiB^2*Lam*(Wmass^2 - Zmass^2) + CphiB*(4*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(4*CphiBox*Wmass^2 - 4*CphiBox*Zmass^2 + CphiD*Zmass^2)))), 0}, {I*gc12*(8*Sqrt[2]*Gf^2 + 16*(CphiBox + CphiD)*Gf*Lam + Sqrt[2]*(16*CphiBox^2 + 12*CphiBox*CphiD - 9*CphiD^2)*Lam^2)*Zmass^4*Sqrt[-Wmass^2 + Zmass^2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc13*SUNF[e1x2, e2x2, e3x2]), 0}, {gc13*SUNF[e1x2, e2x2, e3x2], 0}, {gc13*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc13*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc13*SUNF[e1x2, e2x2, e3x2]), 0}, {gc13*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc14*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc14*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc14*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc15[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc15[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc16[e1x2, e2x2], 0}, {I*gc16[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc17[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc17[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ V[1] , V[3] , -V[3] ] == {{I*gc18*(-(CphiD^2*Lam^2*Wmass^4) + 8*Sqrt[2]*CphiD*Gf*Lam*Wmass^2*(Wmass^2 - Zmass^2) + 64*Gf^2*(Wmass^2 - Zmass^2)^2), 0}, {(I*gc18*(-Wmass^2 + Zmass^2)*(64*Gf^2*(Wmass^2 - Zmass^2)^2 + 8*Sqrt[2]*Gf*Lam*Wmass*(Wmass^2 - Zmass^2)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) - Lam^2*Wmass*(CphiD^2*Wmass^3 + 8*CphiD*CphiWB*(-Wmass^2 + Zmass^2)^(3/2) + 32*(CphiB + CphiW)*CphiWB*(-Wmass^2 + Zmass^2)^(3/2))))/((Wmass - Zmass)*(Wmass + Zmass)), 0}, {I*gc18*(CphiD^2*Lam^2*Wmass^4 - 64*Gf^2*(Wmass^2 - Zmass^2)^2 + 8*Sqrt[2]*CphiD*Gf*Lam*Wmass^2*(-Wmass^2 + Zmass^2)), 0}, {((-I)*gc18*(-Wmass^2 + Zmass^2)*(64*Gf^2*(Wmass^2 - Zmass^2)^2 + 8*Sqrt[2]*Gf*Lam*Wmass*(Wmass^2 - Zmass^2)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) - Lam^2*Wmass*(CphiD^2*Wmass^3 + 8*CphiD*CphiWB*(-Wmass^2 + Zmass^2)^(3/2) + 32*(CphiB + CphiW)*CphiWB*(-Wmass^2 + Zmass^2)^(3/2))))/((Wmass - Zmass)*(Wmass + Zmass)), 0}, {((-I)*gc18*(-Wmass^2 + Zmass^2)*(64*Gf^2*(Wmass^2 - Zmass^2)^2 + 8*Sqrt[2]*Gf*Lam*Wmass*(Wmass^2 - Zmass^2)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) - Lam^2*Wmass*(CphiD^2*Wmass^3 + 8*CphiD*CphiWB*(-Wmass^2 + Zmass^2)^(3/2) + 32*(CphiB + CphiW)*CphiWB*(-Wmass^2 + Zmass^2)^(3/2))))/((Wmass - Zmass)*(Wmass + Zmass)), 0}, {(I*gc18*(-Wmass^2 + Zmass^2)*(64*Gf^2*(Wmass^2 - Zmass^2)^2 + 8*Sqrt[2]*Gf*Lam*Wmass*(Wmass^2 - Zmass^2)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) - Lam^2*Wmass*(CphiD^2*Wmass^3 + 8*CphiD*CphiWB*(-Wmass^2 + Zmass^2)^(3/2) + 32*(CphiB + CphiW)*CphiWB*(-Wmass^2 + Zmass^2)^(3/2))))/((Wmass - Zmass)*(Wmass + Zmass)), 0}},

C[ S[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc19*(8*Sqrt[2]*CphiW^2*Lam*(Wmass^2 - Zmass^2) + 2*CphiWB*(2*Gf + Sqrt[2]*(CphiB + CphiBox)*Lam)*Wmass*Sqrt[-Wmass^2 + Zmass^2] + CphiW*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(4*CphiBox*Wmass^2 - 4*CphiBox*Zmass^2 + CphiD*Zmass^2 + 6*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2]))), 0}, {I*CphiW*gc19*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(8*CphiW*Wmass^2 + CphiD*Zmass^2 - 8*CphiW*Zmass^2 + 4*CphiBox*(Wmass^2 - Zmass^2) + 4*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])), 0}, {I*gc19*(8*Sqrt[2]*CphiW^2*Lam*(Wmass^2 - Zmass^2) + 2*CphiWB*(2*Gf + Sqrt[2]*(CphiB + CphiBox)*Lam)*Wmass*Sqrt[-Wmass^2 + Zmass^2] + CphiW*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(4*CphiBox*Wmass^2 - 4*CphiBox*Zmass^2 + CphiD*Zmass^2 + 6*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2]))), 0}, {(-I)*CphiW*gc19*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(8*CphiW*Wmass^2 + CphiD*Zmass^2 - 8*CphiW*Zmass^2 + 4*CphiBox*(Wmass^2 - Zmass^2) + 4*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])), 0}, {(-I)*CphiW*gc19*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(8*CphiW*Wmass^2 + CphiD*Zmass^2 - 8*CphiW*Zmass^2 + 4*CphiBox*(Wmass^2 - Zmass^2) + 4*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])), 0}, {I*CphiW*gc19*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(8*CphiW*Wmass^2 + CphiD*Zmass^2 - 8*CphiW*Zmass^2 + 4*CphiBox*(Wmass^2 - Zmass^2) + 4*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])), 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc20*(16*Sqrt[2]*CphiW^2*Lam*(Wmass^2 - Zmass^2) + CphiWB*(8*Gf + Sqrt[2]*(4*CphiB + 8*CphiBox - CphiD)*Lam)*Wmass*Sqrt[-Wmass^2 + Zmass^2] + 2*CphiW*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(8*CphiBox*Wmass^2 - CphiD*Wmass^2 - 8*CphiBox*Zmass^2 + 2*CphiD*Zmass^2 + 6*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2]))), 0}, {(2*I)*CphiW*gc20*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(-(CphiD*Wmass^2) + 8*CphiW*Wmass^2 + 2*CphiD*Zmass^2 - 8*CphiW*Zmass^2 + 8*CphiBox*(Wmass^2 - Zmass^2) + 4*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])), 0}, {I*gc20*(16*Sqrt[2]*CphiW^2*Lam*(Wmass^2 - Zmass^2) + CphiWB*(8*Gf + Sqrt[2]*(4*CphiB + 8*CphiBox - CphiD)*Lam)*Wmass*Sqrt[-Wmass^2 + Zmass^2] + 2*CphiW*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(8*CphiBox*Wmass^2 - CphiD*Wmass^2 - 8*CphiBox*Zmass^2 + 2*CphiD*Zmass^2 + 6*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2]))), 0}, {(-2*I)*CphiW*gc20*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(-(CphiD*Wmass^2) + 8*CphiW*Wmass^2 + 2*CphiD*Zmass^2 - 8*CphiW*Zmass^2 + 8*CphiBox*(Wmass^2 - Zmass^2) + 4*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])), 0}, {(-2*I)*CphiW*gc20*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(-(CphiD*Wmass^2) + 8*CphiW*Wmass^2 + 2*CphiD*Zmass^2 - 8*CphiW*Zmass^2 + 8*CphiBox*(Wmass^2 - Zmass^2) + 4*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])), 0}, {(2*I)*CphiW*gc20*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(-(CphiD*Wmass^2) + 8*CphiW*Wmass^2 + 2*CphiD*Zmass^2 - 8*CphiW*Zmass^2 + 8*CphiBox*(Wmass^2 - Zmass^2) + 4*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])), 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc21, 0}, {(-I)*gc21, 0}, {(2*I)*gc21, 0}},

C[ S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc22, 0}, {(-I)*gc22, 0}, {(2*I)*gc22, 0}},

C[ S[1] , S[1] , V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc23, 0}, {(-I)*gc23, 0}, {(2*I)*gc23, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc24*((64*Gf^2 + 8*Sqrt[2]*CphiD*Gf*Lam - CphiD^2*Lam^2)*Wmass*Sqrt[-Wmass^2 + Zmass^2] - 8*CphiWB*Lam*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2))), 0}, {(-I)*gc24*((-64*Gf^2 - 8*Sqrt[2]*CphiD*Gf*Lam + CphiD^2*Lam^2)*Wmass*Sqrt[-Wmass^2 + Zmass^2] + 8*CphiWB*Lam*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2))), 0}, {(-I)*gc24*((-64*Gf^2 - 8*Sqrt[2]*CphiD*Gf*Lam + CphiD^2*Lam^2)*Wmass*Sqrt[-Wmass^2 + Zmass^2] + 8*CphiWB*Lam*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2))), 0}, {(-I)*gc24*(64*Gf^2 + 8*Sqrt[2]*CphiD*Gf*Lam - CphiD^2*Lam^2)*Wmass*Sqrt[-Wmass^2 + Zmass^2], 0}, {I*gc24*((-64*Gf^2 - 8*Sqrt[2]*CphiD*Gf*Lam + CphiD^2*Lam^2)*Wmass*Sqrt[-Wmass^2 + Zmass^2] + 8*CphiWB*Lam*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2))), 0}, {I*gc24*(64*Gf^2 + 8*Sqrt[2]*CphiD*Gf*Lam - CphiD^2*Lam^2)*Wmass*Sqrt[-Wmass^2 + Zmass^2], 0}},

C[ S[1] , V[3] , -V[3] , V[2] ] == {{(-8*I)*CphiW*gc25*(2*Gf*Wmass + Sqrt[2]*Lam*(CphiBox*Wmass + 2*CphiW*Wmass + CphiWB*Sqrt[-Wmass^2 + Zmass^2])), 0}, {(8*I)*CphiW*gc25*(2*Gf*Wmass + Sqrt[2]*Lam*(CphiBox*Wmass + 2*CphiW*Wmass + CphiWB*Sqrt[-Wmass^2 + Zmass^2])), 0}, {(8*I)*CphiW*gc25*(2*Gf*Wmass + Sqrt[2]*Lam*(CphiBox*Wmass + 2*CphiW*Wmass + CphiWB*Sqrt[-Wmass^2 + Zmass^2])), 0}, {(-I)*gc25*(8*CphiW*(2*Gf + Sqrt[2]*(CphiBox + 2*CphiW)*Lam)*Wmass - (CphiWB*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(4*CphiBox*Wmass^2 + 12*CphiW*Wmass^2 - 4*CphiBox*Zmass^2 + CphiD*Zmass^2 - 12*CphiW*Zmass^2 + 4*CphiB*(Wmass^2 - Zmass^2))))/Sqrt[-Wmass^2 + Zmass^2]), 0}, {(-8*I)*CphiW*gc25*(2*Gf*Wmass + Sqrt[2]*Lam*(CphiBox*Wmass + 2*CphiW*Wmass + CphiWB*Sqrt[-Wmass^2 + Zmass^2])), 0}, {I*gc25*(8*CphiW*(2*Gf + Sqrt[2]*(CphiBox + 2*CphiW)*Lam)*Wmass - (CphiWB*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(4*CphiBox*Wmass^2 + 12*CphiW*Wmass^2 - 4*CphiBox*Zmass^2 + CphiD*Zmass^2 - 12*CphiW*Zmass^2 + 4*CphiB*(Wmass^2 - Zmass^2))))/Sqrt[-Wmass^2 + Zmass^2]), 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*CphiW*gc26*Sqrt[-Wmass^2 + Zmass^2]*(8*Gf*Wmass + Sqrt[2]*Lam*(8*CphiBox*Wmass - CphiD*Wmass + 8*CphiW*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2])), 0}, {(2*I)*CphiW*gc26*Sqrt[-Wmass^2 + Zmass^2]*(8*Gf*Wmass + Sqrt[2]*Lam*(8*CphiBox*Wmass - CphiD*Wmass + 8*CphiW*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2])), 0}, {(2*I)*CphiW*gc26*Sqrt[-Wmass^2 + Zmass^2]*(8*Gf*Wmass + Sqrt[2]*Lam*(8*CphiBox*Wmass - CphiD*Wmass + 8*CphiW*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2])), 0}, {(-I)*gc26*(2*CphiW*(8*Gf + Sqrt[2]*(8*CphiBox - CphiD + 8*CphiW)*Lam)*Wmass*Sqrt[-Wmass^2 + Zmass^2] + CphiWB*(-8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(-4*CphiB*Wmass^2 - 8*CphiBox*Wmass^2 + CphiD*Wmass^2 - 12*CphiW*Wmass^2 + 4*CphiB*Zmass^2 + 8*CphiBox*Zmass^2 - 2*CphiD*Zmass^2 + 12*CphiW*Zmass^2))), 0}, {(-2*I)*CphiW*gc26*Sqrt[-Wmass^2 + Zmass^2]*(8*Gf*Wmass + Sqrt[2]*Lam*(8*CphiBox*Wmass - CphiD*Wmass + 8*CphiW*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2])), 0}, {I*gc26*(2*CphiW*(8*Gf + Sqrt[2]*(8*CphiBox - CphiD + 8*CphiW)*Lam)*Wmass*Sqrt[-Wmass^2 + Zmass^2] + CphiWB*(-8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(-4*CphiB*Wmass^2 - 8*CphiBox*Wmass^2 + CphiD*Wmass^2 - 12*CphiW*Wmass^2 + 4*CphiB*Zmass^2 + 8*CphiBox*Zmass^2 - 2*CphiD*Zmass^2 + 12*CphiW*Zmass^2))), 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc27, 0}, {(-I)*gc27, 0}, {(2*I)*gc27, 0}},

C[ S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc28, 0}, {(-I)*gc28, 0}, {(2*I)*gc28, 0}},

C[ S[1] , S[1] , V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc29, 0}, {(-I)*gc29, 0}, {(2*I)*gc29, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc30, 0}, {I*gc30, 0}, {(I*Sqrt[2]*gc30*(64*Gf^2*Wmass*(Wmass^2 - Zmass^2)^2 + 8*Sqrt[2]*Gf*Lam*(2*Wmass^4 - 3*Wmass^2*Zmass^2 + Zmass^4)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) + Lam^2*(-(CphiD^2*Wmass*Zmass^4) - 32*CphiWB^2*Wmass*(Wmass^2 - Zmass^2)^2 + 32*CphiWB*(-Wmass^2 + Zmass^2)^(3/2)*(-(CphiD*Wmass^2) + CphiB*(-2*Wmass^2 + Zmass^2) + CphiW*(-2*Wmass^2 + Zmass^2)))))/(64*Sqrt[2]*Gf^2*Wmass*(Wmass^2 - Zmass^2)^2 + 16*Gf*Lam*(2*Wmass^4 - 3*Wmass^2*Zmass^2 + Zmass^4)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) + Sqrt[2]*Lam^2*(-(CphiD^2*Wmass*Zmass^4) - 32*CphiWB^2*Wmass*(Wmass^2 - Zmass^2)^2 + 32*CphiWB*(-Wmass^2 + Zmass^2)^(3/2)*(-(CphiD*Wmass^2) + CphiB*(-2*Wmass^2 + Zmass^2) + CphiW*(-2*Wmass^2 + Zmass^2)))), 0}},

C[ S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc31, 0}, {I*gc31, 0}, {I*gc31, 0}},

C[ S[1] , S[1] , V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc32, 0}, {I*gc32, 0}, {I*gc32, 0}},

C[ S[1] , S[1] , S[1] , V[2] , V[2] ] == {{((-3*I)*CphiD*Lam*(-8*Gf + Sqrt[2]*(-12*CphiBox + 5*CphiD)*Lam)*Zmass^2)/(2^(3/4)*Sqrt[Gf]), 0}},

C[ S[1] , S[1] , S[1] , S[1] , V[2] , V[2] ] == {{(6*I)*CphiD*Lam*(2*Sqrt[2]*Gf + 8*CphiBox*Lam - 3*CphiD*Lam)*Zmass^2, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc35, 0}, {(-I)*gc35, 0}, {(2*I)*gc35, 0}},

C[ S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc36, 0}, {(-I)*gc36, 0}, {(2*I)*gc36, 0}},

C[ S[1] , S[1] , V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc37, 0}, {(-I)*gc37, 0}, {(2*I)*gc37, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc38*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc38*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc39*IndexDelta[e1x2, e2x2], 0}, {I*gc39*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc40*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc40*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc41*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc41*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc42*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc42*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc43[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc44[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc45[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc46[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc47L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc47R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc48L*IndexDelta[e1x2, e2x2], 0}, {I*gc48R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc49L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc49R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc50*IndexDelta[e1x2, e2x2], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> -1/32*1/(2^(3/4)*Gf^(5/2)),
     gc2 -> -1/8*1/Gf^2,
     gc5 -> -((Lam*(4*CphiWB^2*Lam*Wmass^2*Sqrt[-Wmass^2 + Zmass^2] + CphiWB*Wmass*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiBox*Wmass^2 + CphiD*Wmass^2 + 12*CphiW*Wmass^2 - 4*CphiBox*Zmass^2 - 12*CphiW*Zmass^2 + 4*CphiB*(Wmass^2 - Zmass^2))) + Sqrt[-Wmass^2 + Zmass^2]*(8*CphiB^2*Lam*Wmass^2 + CphiB*(4*Sqrt[2]*Gf + (4*CphiBox + CphiD)*Lam)*Wmass^2 - CphiW*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiBox*(Wmass^2 - Zmass^2) + 8*CphiW*(Wmass^2 - Zmass^2) + CphiD*(Wmass^2 + Zmass^2))))))/(2^(3/4)*Gf^(3/2)*Zmass^2*Sqrt[-Wmass^2 + Zmass^2])),
     gc6 -> -1/2*(Lam*(8*Sqrt[2]*CphiB^2*Lam*Wmass^2 + 4*Sqrt[2]*CphiWB^2*Lam*Wmass^2 + 8*CphiB*(Gf + Sqrt[2]*CphiBox*Lam)*Wmass^2 + (CphiWB*Wmass*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(8*CphiBox*Wmass^2 + 12*CphiW*Wmass^2 - 8*CphiBox*Zmass^2 + CphiD*Zmass^2 - 12*CphiW*Zmass^2 + 4*CphiB*(Wmass^2 - Zmass^2))))/Sqrt[-Wmass^2 + Zmass^2] - 2*CphiW*(4*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(4*CphiW*Wmass^2 + CphiD*Zmass^2 - 4*CphiW*Zmass^2 + 4*CphiBox*(Wmass^2 - Zmass^2)))))/(Gf*Zmass^2),
     gc7 -> 1/(16*2^(3/4)*Gf^(3/2)),
     gc8 -> 1/(4*Gf),
     gc9 -> -1/2*(Lam*(8*Sqrt[2]*CphiB*Gf*Wmass*(Wmass^2 - Zmass^2) - 8*Sqrt[2]*CphiW*Gf*Wmass*(Wmass^2 - Zmass^2) + 16*CphiB^2*Lam*Wmass*(Wmass^2 - Zmass^2) - 16*CphiW^2*Lam*Wmass*(Wmass^2 - Zmass^2) + 8*CphiWB^2*Lam*Wmass*(Wmass^2 - Zmass^2) - CphiWB*Sqrt[-Wmass^2 + Zmass^2]*(4*Sqrt[2]*Gf*(2*Wmass^2 - Zmass^2) + Lam*(8*CphiBox*Wmass^2 + 2*CphiD*Wmass^2 - 4*CphiBox*Zmass^2 + CphiD*Zmass^2)) - 2*CphiW*Lam*(CphiD*Wmass^3 + 6*CphiWB*(2*Wmass^2 - Zmass^2)*Sqrt[-Wmass^2 + Zmass^2] + 4*CphiBox*(Wmass^3 - Wmass*Zmass^2)) + 2*CphiB*Lam*(CphiD*Wmass^3 + 2*CphiWB*(-2*Wmass^2 + Zmass^2)*Sqrt[-Wmass^2 + Zmass^2] + 4*CphiBox*(Wmass^3 - Wmass*Zmass^2))))/(2^(3/4)*Gf^(3/2)*Zmass^2*Sqrt[-Wmass^2 + Zmass^2]),
     gc10 -> -1/2*(Lam*(8*Sqrt[2]*CphiB^2*Lam*Wmass*(Wmass^2 - Zmass^2) + 4*Sqrt[2]*CphiWB^2*Lam*Wmass*(Wmass^2 - Zmass^2) + 8*Sqrt[2]*CphiW^2*Lam*Wmass*(-Wmass^2 + Zmass^2) + 8*CphiB*Gf*(Wmass^3 - Wmass*Zmass^2) - 8*CphiW*Gf*(Wmass^3 - Wmass*Zmass^2) - CphiWB*Sqrt[-Wmass^2 + Zmass^2]*(Gf*(8*Wmass^2 - 4*Zmass^2) + Sqrt[2]*Lam*(8*CphiBox*Wmass^2 - 4*CphiBox*Zmass^2 + CphiD*Zmass^2)) - Sqrt[2]*CphiW*Lam*(CphiD*Wmass*Zmass^2 + 6*CphiWB*(2*Wmass^2 - Zmass^2)*Sqrt[-Wmass^2 + Zmass^2] + 8*CphiBox*(Wmass^3 - Wmass*Zmass^2)) + Sqrt[2]*CphiB*Lam*(CphiD*Wmass*Zmass^2 + 2*CphiWB*(-2*Wmass^2 + Zmass^2)*Sqrt[-Wmass^2 + Zmass^2] + 8*CphiBox*(Wmass^3 - Wmass*Zmass^2))))/(Gf*Zmass^2*Sqrt[-Wmass^2 + Zmass^2]),
     gc11 -> 1/(16*2^(3/4)*Gf^(3/2)*Zmass^2*Sqrt[-Wmass^2 + Zmass^2]),
     gc12 -> 1/(4*Gf*Zmass^2*Sqrt[-Wmass^2 + Zmass^2]),
     gc13 -> 2*Sqrt[aS]*Sqrt[Pi],
     gc14 -> -4*aS*Pi,
     gc15[e1x2_, e2x2_] -> -1/32*((64*Gf^2 + 8*Sqrt[2]*(4*CphiBox - CphiD)*Gf*Lam + 3*(-4*CphiBox + CphiD)^2*Lam^2)*fmd[e1x2, e2x2])/(2^(3/4)*Gf^(3/2)),
     gc16[e1x2_, e2x2_] -> -1/32*((64*Gf^2 + 8*Sqrt[2]*(4*CphiBox - CphiD)*Gf*Lam + 3*(-4*CphiBox + CphiD)^2*Lam^2)*fml[e1x2, e2x2])/(2^(3/4)*Gf^(3/2)),
     gc17[e1x2_, e2x2_] -> -1/32*((64*Gf^2 + 8*Sqrt[2]*(4*CphiBox - CphiD)*Gf*Lam + 3*(-4*CphiBox + CphiD)^2*Lam^2)*fmu[e1x2, e2x2])/(2^(3/4)*Gf^(3/2)),
     gc18 -> Wmass/(16*2^(3/4)*Gf^(3/2)*Zmass*(-Wmass^2 + Zmass^2)^(3/2)),
     gc19 -> -((Lam*Wmass)/(Gf*Zmass*Sqrt[-Wmass^2 + Zmass^2])),
     gc20 -> -((Lam*Wmass)/(2^(3/4)*Sqrt[Gf]*Zmass*Sqrt[-Wmass^2 + Zmass^2])),
     gc21 -> -((Wmass^2*((2*Sqrt[2]*CphiWB^2*Lam^2*Wmass^2)/Gf - 2*(CphiD*Lam*Wmass^2 + 2*Sqrt[2]*Gf*(Wmass^2 - Zmass^2)) + (CphiWB*Lam*Wmass*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(2*CphiD*Wmass^2 + 4*CphiW*Wmass^2 - CphiD*Zmass^2 - 4*CphiW*Zmass^2 + 4*CphiB*(Wmass^2 - Zmass^2))))/(Gf*Sqrt[-Wmass^2 + Zmass^2])))/Zmass^2),
     gc22 -> (-2*2^(1/4)*CphiW*Lam*Wmass^2*(8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(CphiD*Wmass^2 + 8*CphiW*Wmass^2 + CphiD*Zmass^2 - 8*CphiW*Zmass^2 + 4*CphiBox*(Wmass^2 - Zmass^2) + 8*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])))/(Sqrt[Gf]*Zmass^2),
     gc23 -> (-8*CphiW*Lam*Wmass^2*(2*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiW*Wmass^2 + CphiD*Zmass^2 - 4*CphiW*Zmass^2 + 4*CphiBox*(Wmass^2 - Zmass^2) + 4*CphiWB*Wmass*Sqrt[-Wmass^2 + Zmass^2])))/Zmass^2,
     gc24 -> -1/16*Wmass/(2^(3/4)*Gf^(3/2)*Zmass*Sqrt[-Wmass^2 + Zmass^2]),
     gc25 -> (Lam*Wmass)/(2*Gf*Zmass),
     gc26 -> (Lam*Wmass)/(2^(3/4)*Sqrt[Gf]*Zmass*Sqrt[-Wmass^2 + Zmass^2]),
     gc27 -> 4*Sqrt[2]*Gf*Wmass^2,
     gc28 -> (-2*2^(1/4)*CphiW*Lam*(8*Gf + Sqrt[2]*(4*CphiBox - CphiD + 8*CphiW)*Lam)*Wmass^2)/Sqrt[Gf],
     gc29 -> -8*CphiW*Lam*(2*Sqrt[2]*Gf + (4*CphiBox - CphiD + 4*CphiW)*Lam)*Wmass^2,
     gc30 -> -1/16*(Wmass^2*(64*Sqrt[2]*Gf^2*Wmass*(Wmass^2 - Zmass^2)^2 + 16*Gf*Lam*(2*Wmass^4 - 3*Wmass^2*Zmass^2 + Zmass^4)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) + Sqrt[2]*Lam^2*(-(CphiD^2*Wmass*Zmass^4) - 32*CphiWB^2*Wmass*(Wmass^2 - Zmass^2)^2 + 32*CphiWB*(-Wmass^2 + Zmass^2)^(3/2)*(-(CphiD*Wmass^2) + CphiB*(-2*Wmass^2 + Zmass^2) + CphiW*(-2*Wmass^2 + Zmass^2)))))/(Gf*(Wmass - Zmass)*Zmass^2*(Wmass + Zmass)*Sqrt[-Wmass^2 + Zmass^2]),
     gc31 -> (2*2^(1/4)*CphiW*Lam*Wmass^2*(8*Gf*(Wmass^3 - Wmass*Zmass^2) + Sqrt[2]*Lam*(CphiD*Wmass^3 + 8*CphiW*Wmass^3 - 8*CphiW*Wmass*Zmass^2 + 8*CphiWB*Wmass^2*Sqrt[-Wmass^2 + Zmass^2] - 4*CphiWB*Zmass^2*Sqrt[-Wmass^2 + Zmass^2] + 4*CphiBox*(Wmass^3 - Wmass*Zmass^2))))/(Sqrt[Gf]*Zmass^2*Sqrt[-Wmass^2 + Zmass^2]),
     gc32 -> (4*CphiW*Lam*Wmass^2*(4*Sqrt[2]*Gf*Wmass*(Wmass^2 - Zmass^2) + Lam*(8*CphiW*Wmass^3 + CphiD*Wmass*Zmass^2 - 8*CphiW*Wmass*Zmass^2 + 8*CphiWB*Wmass^2*Sqrt[-Wmass^2 + Zmass^2] - 4*CphiWB*Zmass^2*Sqrt[-Wmass^2 + Zmass^2] + 8*CphiBox*(Wmass^3 - Wmass*Zmass^2))))/(Zmass^2*Sqrt[-Wmass^2 + Zmass^2]),
     gc35 -> -((Wmass^2*(2*(2*Sqrt[2]*Gf + CphiD*Lam)*Wmass^2 + (2*Sqrt[2]*CphiWB^2*Lam^2*(-Wmass^2 + Zmass^2))/Gf + (CphiWB*Lam*Wmass*(-8*Gf*(Wmass^2 - Zmass^2) + Sqrt[2]*Lam*(-4*CphiB*Wmass^2 - 2*CphiD*Wmass^2 - 4*CphiW*Wmass^2 + 4*CphiB*Zmass^2 + CphiD*Zmass^2 + 4*CphiW*Zmass^2)))/(Gf*Sqrt[-Wmass^2 + Zmass^2])))/Zmass^2),
     gc36 -> (2*2^(1/4)*CphiW*Lam*Wmass^3*(8*Gf*Wmass + Sqrt[2]*Lam*(4*CphiBox*Wmass + CphiD*Wmass + 8*CphiW*Wmass + 8*CphiWB*Sqrt[-Wmass^2 + Zmass^2])))/(Sqrt[Gf]*Zmass^2),
     gc37 -> (16*CphiW*Lam*Wmass^3*(Sqrt[2]*Gf*Wmass + 2*Lam*(CphiBox*Wmass + CphiW*Wmass + CphiWB*Sqrt[-Wmass^2 + Zmass^2])))/Zmass^2,
     gc38 -> -1/48*(Wmass*(64*Gf^2*(Wmass^2 - Zmass^2)^2 + 8*Sqrt[2]*Gf*Lam*Wmass*(Wmass^2 - Zmass^2)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) - Lam^2*Wmass*(CphiD^2*Wmass^3 + 8*CphiD*CphiWB*(-Wmass^2 + Zmass^2)^(3/2) + 32*(CphiB + CphiW)*CphiWB*(-Wmass^2 + Zmass^2)^(3/2))))/(2^(3/4)*Gf^(3/2)*(Wmass - Zmass)*Zmass*(Wmass + Zmass)*Sqrt[-Wmass^2 + Zmass^2]),
     gc39 -> -1/16*(Wmass*(64*Gf^2*(Wmass^2 - Zmass^2)^2 + 8*Sqrt[2]*Gf*Lam*Wmass*(Wmass^2 - Zmass^2)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) - Lam^2*Wmass*(CphiD^2*Wmass^3 + 8*CphiD*CphiWB*(-Wmass^2 + Zmass^2)^(3/2) + 32*(CphiB + CphiW)*CphiWB*(-Wmass^2 + Zmass^2)^(3/2))))/(2^(3/4)*Gf^(3/2)*(Wmass - Zmass)*Zmass*(Wmass + Zmass)*Sqrt[-Wmass^2 + Zmass^2]),
     gc40 -> (Wmass*(64*Gf^2*(Wmass^2 - Zmass^2)^2 + 8*Sqrt[2]*Gf*Lam*Wmass*(Wmass^2 - Zmass^2)*(CphiD*Wmass + 4*CphiWB*Sqrt[-Wmass^2 + Zmass^2]) - Lam^2*Wmass*(CphiD^2*Wmass^3 + 8*CphiD*CphiWB*(-Wmass^2 + Zmass^2)^(3/2) + 32*(CphiB + CphiW)*CphiWB*(-Wmass^2 + Zmass^2)^(3/2))))/(24*2^(3/4)*Gf^(3/2)*(Wmass - Zmass)*Zmass*(Wmass + Zmass)*Sqrt[-Wmass^2 + Zmass^2]),
     gc41 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc42 -> -2*Sqrt[aS]*Sqrt[Pi],
     gc43[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Conjugate[Ul[e2x2, e1x2]]),
     gc44[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Kq[e1x2, e2x2]),
     gc45[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Conjugate[Kq[e2x2, e1x2]]),
     gc46[e1x2_, e2x2_] -> -(2^(3/4)*Sqrt[Gf]*Wmass*Ul[e1x2, e2x2]),
     gc47L -> (Sqrt[-Wmass^2 + Zmass^2]*(8*Sqrt[2]*CphiD*Gf*Lam*(2*Wmass^2 - Zmass^2) + 64*Gf^2*(2*Wmass^2 + Zmass^2) + CphiD^2*Lam^2*(-2*Wmass^2 + 3*Zmass^2)) - 16*CphiWB*Lam*Wmass*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2)))/(96*2^(3/4)*Gf^(3/2)*Zmass*Sqrt[-Wmass^2 + Zmass^2]),
     gc47R -> (-(Sqrt[-Wmass^2 + Zmass^2]*(-64*Gf^2*(Wmass^2 - Zmass^2) - 8*Sqrt[2]*CphiD*Gf*Lam*(Wmass^2 + Zmass^2) + CphiD^2*Lam^2*(Wmass^2 + 3*Zmass^2))) - 8*CphiWB*Lam*Wmass*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2)))/(48*2^(3/4)*Gf^(3/2)*Zmass*Sqrt[-Wmass^2 + Zmass^2]),
     gc48L -> (Sqrt[-Wmass^2 + Zmass^2]*(64*Gf^2*(2*Wmass^2 - Zmass^2) + 8*Sqrt[2]*CphiD*Gf*Lam*(2*Wmass^2 + Zmass^2) - CphiD^2*Lam^2*(2*Wmass^2 + 3*Zmass^2)) - 16*CphiWB*Lam*Wmass*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2)))/(32*2^(3/4)*Gf^(3/2)*Zmass*Sqrt[-Wmass^2 + Zmass^2]),
     gc48R -> (-(Sqrt[-Wmass^2 + Zmass^2]*(-64*Gf^2*(Wmass^2 - Zmass^2) - 8*Sqrt[2]*CphiD*Gf*Lam*(Wmass^2 + Zmass^2) + CphiD^2*Lam^2*(Wmass^2 + 3*Zmass^2))) - 8*CphiWB*Lam*Wmass*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2)))/(16*2^(3/4)*Gf^(3/2)*Zmass*Sqrt[-Wmass^2 + Zmass^2]),
     gc49L -> (Sqrt[-Wmass^2 + Zmass^2]*(-64*Gf^2*(4*Wmass^2 - Zmass^2) - 8*Sqrt[2]*CphiD*Gf*Lam*(4*Wmass^2 + Zmass^2) + CphiD^2*Lam^2*(4*Wmass^2 + 3*Zmass^2)) + 32*CphiWB*Lam*Wmass*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2)))/(96*2^(3/4)*Gf^(3/2)*Zmass*Sqrt[-Wmass^2 + Zmass^2]),
     gc49R -> (Sqrt[-Wmass^2 + Zmass^2]*(-64*Gf^2*(Wmass^2 - Zmass^2) - 8*Sqrt[2]*CphiD*Gf*Lam*(Wmass^2 + Zmass^2) + CphiD^2*Lam^2*(Wmass^2 + 3*Zmass^2)) + 8*CphiWB*Lam*Wmass*(4*Sqrt[2]*Gf*(Wmass^2 - Zmass^2) + Lam*(4*CphiB*Wmass^2 + CphiD*Wmass^2 + 4*CphiW*Wmass^2 - 4*CphiB*Zmass^2 - 4*CphiW*Zmass^2)))/(24*2^(3/4)*Gf^(3/2)*Zmass*Sqrt[-Wmass^2 + Zmass^2]),
     gc50 -> ((-64*Gf^2 + 8*Sqrt[2]*CphiD*Gf*Lam - 3*CphiD^2*Lam^2)*Zmass)/(32*2^(3/4)*Gf^(3/2))};

