(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"SMEFT",
  Authors -> {"A. Dedes, J. Rosiek, M. Ryczkowski, K. Suxho, L. Trifyllis"},
  Version -> "3.02",
  Date -> "24. 04. 2023"};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {NP, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "A",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "g",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mvdiag },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mldiag },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mudiag },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mddiag },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MG0,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MGP,
    Indices -> {} },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]A",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]Z",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "\[Eta]Wp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "\[Eta]Wm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MgW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "\[Eta]G",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
mvdiag[ 1 ] := 0;
mvdiag[ 2 ] := 0;
mvdiag[ 3 ] := 0;
mldiag[ 1 ] := MLE;
mldiag[ 2 ] := MLM;
mldiag[ 3 ] := MLT;
mudiag[ 1, _ ] := MQU;
mudiag[ 1 ] := MQU;
mudiag[ 2, _ ] := MQC;
mudiag[ 2 ] := MQC;
mudiag[ 3, _ ] := MQT;
mudiag[ 3 ] := MQT;
mddiag[ 1, _ ] := MQD;
mddiag[ 1 ] := MQD;
mddiag[ 2, _ ] := MQS;
mddiag[ 2 ] := MQS;
mddiag[ 3, _ ] := MQB;
mddiag[ 3 ] := MQB;
MH[ ___ ] := MH;
MG0[ ___ ] := MG0;
MGP[ ___ ] := MGP;
MgZ[ ___ ] := MgZ;
MgW[ ___ ] := MgW;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ Last["SSS"] ] == {{gc1, 1}, {gc1, 2}, {gc1, 3}},

C[ Last["SSSS"] ] == {{gc2, 1}, {gc2, 2}, {gc2, 3}, {gc2, 4}},

C[ Last["SSVV"] ] == {{S[1], 1}, {S[1], 2}, {V[4, {e1x2}], 3}, {V[4, {e2x2}], 4}},

C[ Last["SSSVV"] ] == {{S[1], 1}, {S[1], 2}, {S[1], 3}, {V[4, {e1x2}], 4}, {V[4, {e2x2}], 5}},

C[ Last["SSSSVV"] ] == {{S[1], 1}, {S[1], 2}, {S[1], 3}, {S[1], 4}, {V[4, {e1x2}], 5}, {V[4, {e2x2}], 6}},

C[ Last["VVV"] ] == {{V[4, {e1x2}], 1}, {V[4, {e2x2}], 2}, {V[4, {e3x2}], 3}},

C[ Last["VVVV"] ] == {{V[4, {e1x2}], 1}, {V[4, {e2x2}], 2}, {V[4, {e3x2}], 3}, {V[4, {e4x2}], 4}},

C[ Last["SSVVV"] ] == {{S[1], 1}, {S[1], 2}, {V[4, {e1x2}], 3}, {V[4, {e2x2}], 4}, {V[4, {e3x2}], 5}},

C[ Last["SSSVVV"] ] == {{S[1], 1}, {S[1], 2}, {S[1], 3}, {V[4, {e1x2}], 4}, {V[4, {e2x2}], 5}, {V[4, {e3x2}], 6}},

C[ Last["SSSSVVV"] ] == {{S[1], 1}, {S[1], 2}, {S[1], 3}, {S[1], 4}, {V[4, {e1x2}], 5}, {V[4, {e2x2}], 6}, {V[4, {e3x2}], 7}},

C[ Last["SSVVVV"] ] == {{S[1], 1}, {S[1], 2}, {V[4, {e1x2}], 3}, {V[4, {e2x2}], 4}, {V[4, {e3x2}], 5}, {V[4, {e4x2}], 6}},

C[ Last["SSSVVVV"] ] == {{S[1], 1}, {S[1], 2}, {S[1], 3}, {V[4, {e1x2}], 4}, {V[4, {e2x2}], 5}, {V[4, {e3x2}], 6}, {V[4, {e4x2}], 7}},

C[ Last["SSSSVVVV"] ] == {{S[1], 1}, {S[1], 2}, {S[1], 3}, {S[1], 4}, {V[4, {e1x2}], 5}, {V[4, {e2x2}], 6}, {V[4, {e3x2}], 7}, {V[4, {e4x2}], 8}},

C[ Last["FFS"] ] == {{-F[4, {e1x2, e1x3}], 1}, {F[4, {e2x2, e2x3}], 2}, {S[1], 3}},

C[ Last["FFS"] ] == {{-F[2, {e1x2}], 1}, {F[2, {e2x2}], 2}, {S[1], 3}},

C[ Last["FFS"] ] == {{-F[3, {e1x2, e1x3}], 1}, {F[3, {e2x2, e2x3}], 2}, {S[1], 3}},

C[ Last["VVV"] ] == {{-(gc17*V[1]), 1}, {-(gc17*V[3]), 2}, {gc17*V[3], 3}},

C[ Last["SVV"] ] == {{-(gc18*S[1]), 1}, {-(gc18*V[3]), 2}, {gc18*V[3], 3}},

C[ Last["SSVV"] ] == {{-(gc19*S[1]), 1}, {-(gc19*S[1]), 2}, {-(gc19*V[3]), 3}, {gc19*V[3], 4}},

C[ Last["VVVV"] ] == {{-(gc20*V[1]), 1}, {-(gc20*V[1]), 2}, {-(gc20*V[3]), 3}, {gc20*V[3], 4}},

C[ Last["VVV"] ] == {{V[3], 1}, {-V[3], 2}, {V[2], 3}},

C[ Last["VVVV"] ] == {{-gc22, 1}, {-gc22, 2}, {gc22, 3}, {gc22, 4}},

C[ Last["VVVV"] ] == {{V[1], 1}, {V[3], 2}, {-V[3], 3}, {V[2], 4}},

C[ Last["SVV"] ] == {{S[1], 1}, {V[2], 2}, {V[2], 3}},

C[ Last["SSVV"] ] == {{S[1], 1}, {S[1], 2}, {V[2], 3}, {V[2], 4}},

C[ Last["VVVV"] ] == {{V[3], 1}, {-V[3], 2}, {V[2], 3}, {V[2], 4}},

C[ Last["FFV"] ] == {{-F[4, {e1x2, e1x3}], 1}, {F[4, {e2x2, e2x3}], 2}, {V[1], 3}},

C[ Last["FFV"] ] == {{-F[2, {e1x2}], 1}, {F[2, {e2x2}], 2}, {V[1], 3}},

C[ Last["FFV"] ] == {{-F[3, {e1x2, e1x3}], 1}, {F[3, {e2x2, e2x3}], 2}, {V[1], 3}},

C[ Last["FFV"] ] == {{-F[4, {e1x2, e1x3}], 1}, {F[4, {e2x2, e2x3}], 2}, {V[4, {e3x2}], 3}},

C[ Last["FFV"] ] == {{-F[3, {e1x2, e1x3}], 1}, {F[3, {e2x2, e2x3}], 2}, {V[4, {e3x2}], 3}},

C[ Last["FFV"] ] == {{-F[1, {e1x2}], 1}, {F[2, {e2x2}], 2}, {V[3], 3}},

C[ Last["FFV"] ] == {{-F[3, {e1x2, e1x3}], 1}, {F[4, {e2x2, e2x3}], 2}, {V[3], 3}},

C[ Last["FFV"] ] == {{gc34*F[4, {e1x2, e1x3}], 1}, {-(gc34*F[3, {e2x2, e2x3}]), 2}, {gc34*V[3], 3}},

C[ Last["FFV"] ] == {{gc35*F[2, {e1x2}], 1}, {-(gc35*F[1, {e2x2}]), 2}, {gc35*V[3], 3}},

C[ Last["FFV"] ] == {{-F[4, {e1x2, e1x3}], 1}, {F[4, {e2x2, e2x3}], 2}, {V[2], 3}},

C[ Last["FFV"] ] == {{-F[2, {e1x2}], 1}, {F[2, {e2x2}], 2}, {V[2], 3}},

C[ Last["FFV"] ] == {{-F[3, {e1x2, e1x3}], 1}, {F[3, {e2x2, e2x3}], 2}, {V[2], 3}},

C[ Last["FFV"] ] == {{-F[1, {e1x2}], 1}, {F[1, {e2x2}], 2}, {V[2], 3}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc1 -> S[1],
     gc2 -> S[1],
     gc17 -> -1,
     gc18 -> -1,
     gc19 -> -1,
     gc20 -> -1,
     gc22 -> -V[3],
     gc34 -> -1,
     gc35 -> -1};

