(* SmeftFR v4.0 package *)
(* I/O routines: code for generating FeynRules parameter files with
internal and external parameters *)



SMEFTParFile = Function[{oplist, TargetFile},
(* generates FeynRules par file including only "active" operators and internal parameters *)
Module[{tmp,date,cfile},

Print["Parameter file in Warsaw basis generated as ", Style[ TargetFile, Bold ] ];

cfile = OpenWrite[TargetFile];

WriteLine[cfile, "(* Generated by SMEFTParFile routine *)"];
date = Date[];
WriteLine[cfile, "(* " <> ToString[date[[3]]] <> "." <>
    ToString[date[[2]]] <> "." <> ToString[date[[1]]] <> " " <>
    ToString[date[[4]]] <> ":" <> ToString[date[[5]]] <> " *)\n"]

WriteLine[cfile, "(* Active operators included in Feynman Rules: " <> ToString[oplist] <> " *)\n"];

(* copy header with fixed definitions first *)
WriteString[cfile, ReadString[FileNameJoin[{SMEFT$Path, "definitions", "smeft_par_head_WB.fr"}]] ];
WriteLine[cfile, "\n"];

(* add input observables in preferred scheme to fix SM Lagrangian parameters;
see file smeft_input_parameters.m *)
WriteLine[cfile, "(* input observables *)\n"];
WriteInputParameter[cfile,#] & /@ SM$InputParameters;

WriteLine[cfile, "(* dim 6 couplings in Warsaw basis *)\n"];
WriteLine[cfile, "(* flavor independent *)\n"];
If[ MemberQ[oplist, # ], WriteInternalScalarEntry[ cfile, # ] ] & /@ SMEFT$ScalarWC;

WriteLine[cfile, "(* flavor dependent *)\n"];
WriteLine[cfile, "(* 2 fermion operators *)\n"];
If[ MemberQ[ Intersection[oplist, SMEFT$TwoFermionicOperators], #[[1]] ] && ! #[[3]], WriteInternalTensor2Entry[ cfile, # ] ] & /@ SMEFT$TensorWC;

WriteLine[cfile, "(* 4 fermion operators *)\n"];
If[ MemberQ[ Intersection[oplist, SMEFT$FourFermionicOperators], #[[1]] ] && ! #[[3]], WriteInternalTensor4Entry[ cfile, # ] ] & /@ SMEFT$TensorWC;

WriteLine[cfile, "(* L or B violating operators *)\n"];
If[ MemberQ[ Intersection[oplist, SMEFT$TwoFermionicOperators], #[[1]] ] && #[[3]], WriteInternalTensor2Entry[ cfile, # ] ] & /@ SMEFT$TensorWC;
If[ MemberQ[ Intersection[oplist, SMEFT$FourFermionicOperators], #[[1]] ] && #[[3]], WriteInternalTensor4Entry[ cfile, # ] ] & /@ SMEFT$TensorWC;

WriteLine[cfile, "(* redefined (mass basis) WCs *)\n"];
WriteLine[cfile, "(* flavor independent *)\n"];
If[ MemberQ[oplist, # ], WriteInternalMassScalarEntry[ cfile, # ] ] & /@  SMEFT$ScalarWC;

WriteLine[cfile, "(* flavor dependent *)\n"];
WriteLine[cfile, "(* 2 fermion operators *)\n"];
If[ MemberQ[ Intersection[oplist, SMEFT$TwoFermionicOperators], #[[1]] ] && ! #[[3]], WriteInternalMassTensorEntry[ cfile, #, False ] ] & /@ SMEFT$TensorWC;

WriteLine[cfile, "(* 4 fermion operators *)\n"];
If[ MemberQ[ Intersection[oplist, SMEFT$FourFermionicOperators], #[[1]] ] && ! #[[3]], WriteInternalMassTensorEntry[ cfile, #, True ] ] & /@ SMEFT$TensorWC;

WriteLine[cfile, "(* L or B violating operators *)\n"];
If[ MemberQ[ Intersection[oplist, SMEFT$TwoFermionicOperators], #[[1]] ] && #[[3]], WriteInternalMassTensorEntry[ cfile, #, False ] ] & /@ SMEFT$TensorWC;
If[ MemberQ[ Intersection[oplist, SMEFT$FourFermionicOperators], #[[1]] ] && #[[3]], WriteInternalMassTensorEntry[ cfile, #, True ] ] & /@ SMEFT$TensorWC;

WriteLine[cfile, "(* NP scale *)\n"];
WriteLine[cfile, "Lam == {"];
WriteLine[cfile, "  ParameterType -> Internal,"];
WriteLine[cfile, "  TeX           -> 1/\[CapitalLambda]^2,"];
WriteLine[cfile, "  Description   -> \"Effective NP scale squared\""];
WriteLine[cfile, "}\n"];

WriteLine[cfile, "}\n"];

(* updates the correct maximal NP and CP interaction orders for model files *)
Get[ FileNameJoin[{SMEFT$Path, "definitions", "smeft_par_io.fr"}] ];
WriteLine[cfile, "M$InteractionOrderHierarchy = ", M$InteractionOrderHierarchy, "\n"];
WriteLine[cfile, "M$InteractionOrderLimit = ",     M$InteractionOrderLimit /.
                                      {NP,__} -> {NP,SMEFT$ExpansionOrder} /.
                                      {CP,__} -> {CP,SMEFT$CPMaxOrder}, "\n"];

Close[TargetFile];

]
(* end of SMEFTParFile *)
]





(* export routine, store Lagrangian and Feynman in mass basis to a file *)
SMEFTOutput[ OptionsPattern[ {TargetFile -> FileNameJoin[{ SMEFT$Path, "output", "smeft_feynman_rules.m" }],
			      ModelFile -> FileNameJoin[{ SMEFT$Path, "output", "smeft_par_MB" }],
			      OverwriteTarget -> True } ]
] :=
Module[{cfile,vlist,laglist,clist,ylist,slist,date,il,tmp,i,j},

vlist = {"LeptonGauge", "LeptonHiggsGauge", "QuarkGauge",
"QuarkHiggsGauge", "QuarkGluon", "GaugeSelf", "GaugeHiggs",
"GluonSelf", "GluonHiggs", "FourLepton", "TwoQuarkTwoLepton",
"FourQuark", "BLViolating"};

laglist = Join[ # <> "Lagrangian" & /@ vlist, {"DeltaLTwoLagrangian"} ];
vlist   = # <> "Vertices" & /@ vlist;

ylist = "SMEFT$" <> # & /@ {"YL", "YD", "YU"};

slist = "SMEFT$" <> # & /@ {"OperatorList", "RxiGaugeStatus",
"MajoranaNeutrino", "Correct4FermionSign", "WB", "MB",
"ExpansionOrder"};

(* generate parameter files in mass basis, 2 options, with real only
   and general (possibly complex) parameters *)
WCXFToSMEFT[ OptionValue[ModelFile] <> ".fr",
             OverwriteTarget -> True,
	     RealParameters  -> Default ];
WCXFToSMEFT[ OptionValue[ModelFile] <> "_real.fr",
             OverwriteTarget -> True,
	     RealParameters  -> True ];
WCXFToSMEFT[ OptionValue[ModelFile] <> "_complex.fr",
             OverwriteTarget -> True,
	     RealParameters  -> False ];

(* check options *)
If [ FileExistsQ[ OptionValue[TargetFile] ] && (! OptionValue[OverwriteTarget]),
    Print["File " <> OptionValue[TargetFile] <> " exists!"];
    TargetExistsQ = AskFunction[ Ask["Overwrite (y/n)?"-> "String"] ][];
];
If[ TargetExistsQ != "y", Print[ "Change name of output file and rerun" ]; Abort[]; ];
Print["Output file will be generated as ",  Style[OptionValue[TargetFile], Bold ] ];

cfile = OpenWrite[OptionValue[TargetFile]];

WriteLine[cfile, "(* Generated by SMEFTOutput routine *)"];
date = Date[];
WriteLine[cfile, "(* " <> ToString[date[[3]]] <> "." <>
    ToString[date[[2]]] <> "." <> ToString[date[[1]]] <> " " <>
    ToString[date[[4]]] <> ":" <> ToString[date[[5]]] <> " *)\n"]
WriteLine[cfile, "(* Active operators included in Lagrangian and Feynman rules: " <> ToString[SMEFT$OperatorList] <> " *)\n"];

WriteLine[cfile, "(* interaction vertices in mass basis *)\n"];
WriteLineEntry[cfile,  # <> " = ", ToExpression[ # ], "\n\n" ] & /@ vlist;
If[ SMEFT$RxiGaugeStatus, WriteLineEntry[cfile, "GhostVertices = ", GhostVertices, "\n\n" ] ];

WriteLine[cfile, "(* Lagrangian in mass basis *)\n"];
WriteLineEntry[cfile,  # <> " = ", ToExpression[ # ], "\n\n" ] & /@ laglist;
If[ SMEFT$RxiGaugeStatus, WriteLineEntry[cfile, "GhostLagrangian = ", GhostLagrangian, "\n\n" ] ];

WriteLine[cfile, "(* corrections to fields and couplings *)\n"];
WriteLine[cfile, "(* SMEFT scheme *)\n"];
NormalizationConstantsExpansion["smeft"];
WriteLineEntry[cfile, "Default$InputSub =", SMEFT$InputSub, "\n\n" ]
WriteLine[cfile, "(* User scheme *)\n"];
NormalizationConstantsExpansion["user"];
WriteLineEntry[cfile, "User$InputSub = ", SMEFT$InputSub, "\n\n" ]
WriteLineEntry[cfile, "SMEFT$InputListStatus = ", True, "\n\n" ]

(* Yukawa couplings *)
Clear[i,j];
WriteLineEntry[cfile,  # <> "[i,j] = ", OptimizeIndex[ ToExpression[ #  <> "[i,j]" ] ], "\n\n" ] & /@ ylist;

WriteLine[cfile, "(* setup variables *)\n"];
WriteLineEntry[cfile,  # <> " = ", ToExpression[ # ], "\n\n" ] & /@ slist;

WriteLineEntry[cfile,  "FeynmanGauge = ",  SMEFT$RxiGaugeStatus, "\n\n" ];

Close[OptionValue[TargetFile]];

]
(* end of SMEFTOutput *)




SMEFTLoadModelFiles = Function[{SMEFTParName},
(* load to FeynRules SMEFT field and parameter definitions *)
If [ SMEFT$MajoranaNeutrino,
  Get[ FileNameJoin[{SMEFT$Path, "definitions", "smeft_fields_WB_majorana.fr"}] ]
,
  Get[ FileNameJoin[{SMEFT$Path, "definitions", "smeft_fields_WB_dirac.fr"}] ]
];

Get[ FileNameJoin[{SMEFT$Path, "output", SMEFTParName}] ];

LoadModel[];
			
(* end of SMEFTLoadModelFiles *)
]




SMEFTLoadLagrangian = Function[{},
(* loads SM and dim6 operator classes *)

(* set gauge *)
SMEFTGaugeRules = If[ ! SMEFT$RxiGaugeStatus, {G0|GP|GPbar ->0}, {} ];
(* Load SM Lagrangian *)
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "00_sm.fr"}] ];
(* Load dim6 operators *)
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "01_X3.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "02_phi6.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "03_psi2phi3.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "04_X2phi2.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "05_psi2Xphi.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "06_psi2phi2D.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "07_LlLl.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "08_RrRr.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "09_LlRr.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "10_LrRl.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "11_BL.fr"}] ];
(* Load dim8 bosonic operators *)
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "201_X4.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "202_phi8.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "203_phi6D2.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "204_phi4D4.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "205_X3phi2.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "206_X2phi4.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "207_X2phi2D2.fr"}] ];
Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "208_Xphi4D2.fr"}] ];	
(* Load dim8 2-fermion operators *)
(* Load dim8 class-209 (psi^2 X^2 H) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "209_psi2X2phi", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "209_psi2X2phi", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-210 (psi^2 X H^3) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "210_psi2Xphi3", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "210_psi2Xphi3", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-211 (psi^2 H^2 D^3) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "211_psi2phi2D3", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "211_psi2phi2D3", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-212 (psi^2 H^5) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "212_psi2phi5", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "212_psi2phi5", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-213 (psi^2 H^4 D) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "213_psi2phi4D", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "213_psi2phi4D", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-214 (psi^2 X^2 D) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "214_psi2X2D", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "214_psi2X2D", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-215 (psi^2 X H^2 D) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "215_psiXphi2D", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "215_psiXphi2D", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-216 (psi^2 X H D^2) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "216_psiXphiD2", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "216_psiXphiD2", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-217 (psi^2 H^3 D^2) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "217_psi2phi3D2", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "217_psi2phi3D2", # <> ".fr"}] ] &
  ]
];
(* Load dim8 4-fermion operators *)
(* Load dim8 class-218 (psi^4 H^2) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "218_psi4phi2", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "218_psi4phi2", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-219 (psi^4 X) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "219_psi4X", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "219_psi4X", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-220 (psi^4 H D) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "220_psi4phiD", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "220_psi4phiD", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-221 (psi^4 D^2) operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "221_psi4D2", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "221_psi4D2", # <> ".fr"}] ] &
  ]
];
(* Load dim8 4-fermion BLV operators *)
(* Load dim8 class-218 (psi^4 H^2) BLV operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "218BL_psi4phi2", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "218BL_psi4phi2", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-219 (psi^4 X) BLV operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "219BL_psi4X", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "219BL_psi4X", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-220 (psi^4 H D) BLV operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "220BL_psi4phiD", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "220BL_psi4phiD", # <> ".fr"}] ] &
  ]
];
(* Load dim8 class-221 (psi^4 D^2) BLV operators on demand *)
Scan[
  Function[op,
    Get[ FileNameJoin[{SMEFT$Path, "lagrangian", "221BL_psi4D2", op <> ".fr"}] ]
  ],
  Select[ SMEFT$OperatorList,
    FileExistsQ[ FileNameJoin[{SMEFT$Path, "lagrangian", "221BL_psi4D2", # <> ".fr"}] ] &
  ]
];
			
(* end of SMEFTLoadLagrangian *)
]




SMEFTToUFO[ Lagrangian_,
	    OptionsPattern[ {Output -> FileNameJoin[{SMEFT$Path, "output", "UFO"}],
                             CorrectIO -> True,
			     AddDecays -> False} ] ] :=
(* generates UFO output and corrects Interaction Order assignments for higher order vertices *)
Module[{target,input,output,outfile,line,char,x,y,tmp},

target = OptionValue[Output];

tmp = Lagrangian;
WriteUFO[ tmp, Output -> target, AddDecays -> OptionValue[AddDecays] ];

(* remove from NP couplings all unnecessary IO assignments *)
If [ OptionValue[CorrectIO] == True,

  Print[ Style[ "\nCorrecting non positive interaction order issues for NP vertices...", Red, Bold ] ];
  input   = FileNameJoin[{target, "couplings.py"}];
  output  = FileNameJoin[{target, "couplings.tmp"}];
  outfile = OpenWrite[output];

  char = 1;
  While[ char =!= EndOfFile,
    line = "";
    char = 1;
    While[ char != 10 && char =!= EndOfFile, (* 10 is char code of "\n" *)
      char  = BinaryRead[input];
      If [ char != 10 && char =!= EndOfFile, line = line <> FromCharacterCode[char] ] ;
    ];

    If [ StringContainsQ[line, "'NP':"],
      line = StringReplace[ line, "'NP':" ~~ x_ ~~ "," ~~ Shortest[y__] ~~ "})" ->
                                  "'NP':" ~~ x ~~ "})" ]
       ];

    If [ char =!= EndOfFile,  WriteLine[outfile,line] ];
  ];

  Close[input];
  Close[outfile];

  DeleteFile[ input ];
  CopyFile  [ output, input ];
  DeleteFile[ output ];

];

Print["\nVertices stored in UFO format in directory", Style[ OptionValue[Output] ,Bold] ];

(* end of SMEFTToUFO *)
]


(* *************************************************** *)
(* low-level functions writing model file entries for scalar and
tensor WCs *)

WriteLineEntry = Function[{cfile,p1,p2,p3},
(* single line output *)

  WriteString[cfile, p1];
  Write[cfile, p2 ];
  WriteString[cfile, p3];

(* end of WriteLineEntry *)
]



WriteInputParameter = Function[{cfile,par},
(* parameter file entry for physical input observable *)
WriteLine[cfile, ToString[ par[[1]] ] <> " == {"];
WriteLine[cfile, "  " <> ToString[ #, InputForm] <> ","] & /@ Drop[ par[[2]], -1 ];
WriteLine[cfile, "  " <> ToString[ par[[ 2, Length[ par[[2]] ] ]], InputForm ] <> "},\n\n"];

(* end of WriteInputParameter *)
]



WriteInternalScalarEntry = Function[{cfile,wc},
(* parameter file entry for scalar Warsaw basis WC *)
(* wc argument is member of ScalarWC list *)
Module[{name},

name = ToString[wc];

WriteLine[cfile, SMEFT$WB <> name <> " == {"];
WriteLine[cfile, "  ParameterType    -> Internal,"];
WriteLine[cfile, "  InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
WriteLine[cfile, "  Definitions      -> {" <> SMEFT$WB <> name <> " -> " <> SMEFT$MB <> name <> "},"];
WriteLine[cfile, "  ComplexParameter -> False,"];
WriteLine[cfile, "  TeX              -> Superscript[" <> SMEFT$WB <> ", " <>
                 StringReplace[name, "phi"->"\[Phi]" ] <> "],"];
WriteLine[cfile, "  Description      -> \"Q" <> name <> " WC\""];
WriteLine[cfile, "},\n\n"];

]
(* end of WriteInternalScalarEntry *)
]



WriteInternalTensor2Entry = Function[{cfile,wc},
(* par file entry for 2-fermion Warsaw basis WC *)
(* wc argument is member of TensorWC list *)
Module[{tex,name},

name = ToString[wc[[1]]];
tex = "Superscript[" <>  SMEFT$WB <> ", " <> StringReplace[name, {"phi"->"\[Phi]", "f"->"\[Phi]"} ] <> "]";

WriteLine[cfile, SMEFT$WB <> name <> " == {"];
WriteLine[cfile, "  ParameterType    -> Internal,"];
WriteLine[cfile, "  Indices          -> {Index[Generation], Index[Generation]},"];
WriteLine[cfile, "  InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
WriteLine[cfile, "  Definitions      -> {" <> SMEFT$WB <> name <>
                 "[ff1_,ff2_] -> Module[{ind1,ind2}, " <>
                 If[ wc[[3]],"Conjugate[",""] <> ToString[ wc[[2]][[1]] ] <>
                 "[ff1,ind1]" <> If[wc[[3]],"] "," "] <> SMEFT$MB <> name <>
                 "[ind1,ind2] Conjugate[" <> ToString[ wc[[2]][[2]] ] <> "[ff2,ind2]] ]},"];
WriteLine[cfile, "  TeX              -> " <> tex <> ","];
WriteLine[cfile, "  Description      -> \"Q" <> name <> " WC\""];
WriteLine[cfile, "},\n\n"];

]
(* end of WriteInternalTensor2Entry *)			
]



WriteInternalTensor4Entry = Function[{cfile,wc},
(* par file entry for 4-fermion Warsaw basis WC *)
(* wc argument is member of TensorWC list *)
Module[{name},

name = ToString[wc[[1]]];

WriteLine[cfile, SMEFT$WB <> name <> " == {"];
WriteLine[cfile, "  ParameterType    -> Internal,"];
WriteLine[cfile, "  Indices          -> {Index[Generation], Index[Generation], Index[Generation], Index[Generation]},"];
WriteLine[cfile, "  InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
WriteLine[cfile, "  Definitions      -> {" <> SMEFT$WB <> name <>
                 "[ff1_,ff2_,ff3_,ff4_] -> Module[{ind1,ind2,ind3,ind4}, " <>
                 If[wc[[3]],"Conjugate[",""] <> ToString[ wc[[2]][[1]] ] <>
                 "[ff1,ind1]" <> If[wc[[3]],"] "," "] <>
                 If[wc[[3]],"Conjugate[",""] <> ToString[ wc[[2]][[3]] ] <>
                 "[ff3,ind3]" <> If[wc[[3]],"] "," "] <> SMEFT$MB <> name <>
                 "[ind1,ind2,ind3,ind4] Conjugate[" <>
                 ToString[ wc[[2]][[2]] ] <> "[ff2,ind2]] Conjugate[" <>
                 ToString[ wc[[2]][[4]] ] <> "[ff4,ind4]] ]},"];
WriteLine[cfile, "  TeX              -> Superscript[" <> SMEFT$WB <> ", " <> name <> "],"];
WriteLine[cfile, "  Description      -> \"Q" <> name <> " WC\""];
WriteLine[cfile, "},\n\n"];

]
(* end of WriteInternalTensor4Entry *)			
]



WriteInternalMassScalarEntry = Function[{cfile,wc},
(* par file entry for scalar mass basis internal WC *)
(* wc argument is member of ScalarWC list *)
Module[{name},

name = ToString[wc];

WriteLine[cfile, SMEFT$MB <> name <> " == {"];
WriteLine[cfile, "  ParameterType    -> Internal,"];
WriteLine[cfile, "  InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
WriteLine[cfile, "  ComplexParameter -> False,"];
WriteLine[cfile, "  TeX              -> Superscript[" <> SMEFT$MB <> ", " <>
	         StringReplace[name, "phi"->"\[Phi]" ] <> "],"];
WriteLine[cfile, "  Description      -> \"Q" <> name <> " WC\""];
WriteLine[cfile, "},\n\n"];

]
(* end of WriteInternalMassScalarEntry *)
]



WriteInternalMassTensorEntry = Function[{cfile,wc,FourFermion},
(* par file entry for 2-fermion mass basis internal WC *)
(* wc argument is member of TensorWC list *)
Module[{tex,name},

name = ToString[wc[[1]]];
tex = "Superscript[" <>  SMEFT$MB <> ", " <> StringReplace[name, {"phi"->"\[Phi]", "f"->"\[Phi]"} ] <> "]";

WriteLine[cfile, SMEFT$MB <> name <> " == {"];
WriteLine[cfile, "  ParameterType    -> Internal,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]" <>
	      If [ FourFermion, ", Index[Generation], Index[Generation]},", "}," ] ];
WriteLine[cfile, "  InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
WriteLine[cfile, "  TeX              -> " <> tex <> ","];
WriteLine[cfile, "  Description      -> \"Q" <> name <> " WC\""];
WriteLine[cfile, "},\n\n"];

]
(* end of WriteInternalMassTensorEntry *)			
]



WriteExternalScalarEntry = Function[{cfile,wc},
(* par file entry for scalar mass basis external WC *)
(* wc argument is association wcname->wcvalue(s) *)
Module[{name},

name = StringDrop[ ToString[ Keys[wc] ], 1];

WriteLine[cfile, " " <> SMEFT$MB <> name <> " == {"];
WriteLine[cfile, "    ParameterType    -> External,"];
WriteLine[cfile, "    InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
WriteLine[cfile, "    Value            -> " <>
                      NumberToString[ Re[ Keys[wc] /. wc ] ] <> "," ];
WriteLine[cfile, "    ComplexParameter -> False,"];
WriteLine[cfile, "    TeX              -> Superscript[" <> SMEFT$MB <> ", " <>
                                          StringReplace[ name, "phi"->"\[Phi]" ] <> "],"];
WriteLine[cfile, "    Description      -> \"Q" <> name <> " WC\""];
WriteLine[cfile, "    },\n\n"];

]
(* end of WriteExternalScalarEntry *)			
]



WriteExternalTensorEntry = Function[{cfile,wc,FourFermion},
(* par file entry for generic fermionic mass basis external WC *)
(* wc argument is association wcname->wcvalue(s) *)
Module[{WC,tex,name},

name = ToString[ Keys[wc] ];
tex = "Superscript[" <>  SMEFT$MB <> ", " <> StringReplace[name, {"phi"->"\[Phi]", "f"->"\[Phi]"} ] <> "]";
WC = Values[wc];

WriteLine[cfile, " " <> SMEFT$MB <> name <> " == {"];
WriteLine[cfile, "    ParameterType    -> External,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]" <>
	      If [ FourFermion, ", Index[Generation], Index[Generation]},", "}," ] ];
WriteLine[cfile, "    InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
WriteLine[cfile, TensorOutputFormat[ ToString /@ Keys[WC], NumberToString /@ Values[WC] ] ];
WriteLine[cfile, "    ComplexParameter -> True,"];
WriteLine[cfile, "    TeX              -> " <> tex <> ","];
WriteLine[cfile, "    Description      -> \"Q" <> name <> " WC\""];
WriteLine[cfile, "    },\n\n"];

]
(* end of WriteExternalTensorEntry *)			
]



WriteUFOTensorEntry = Function[{cfile, parlist, sublist, FourFermion, type},		
(* parameter file entry for fermionic mass basis external WC for UFO
format; 2nd argument is list of independent values for given WC, 3rd
is list od dependent substitutions *)
Module[{par,wcname,name,tex,ind,sind,aa},

wcname = Head[ Keys[parlist][[1]] ];
name = StringDrop[ ToString[wcname], 1];
tex = "Superscript[" <>  SMEFT$MB <> ", " <> StringReplace[name, {"phi"->"\[Phi]", "f"->"\[Phi]"} ] <> "]";

(* split matrix into independent and dependend parameters *)
WriteLine[cfile, " " <> ToString[wcname] <> " == {"];
WriteLine[cfile, "    ParameterType    -> Internal,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]" <>
	      If [ FourFermion, ", Index[Generation], Index[Generation]},", "}," ] ];
WriteLine[cfile, "    InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
WriteLine[cfile, TensorSubFormat[ parlist, sublist ] ];
WriteLine[cfile, "    ComplexParameter -> " <> ToString[ ! type ] <> ","];
WriteLine[cfile, "    TeX              -> " <> tex <> ","];
WriteLine[cfile, "    Description      -> \"Q" <> name <> " WC\""];
WriteLine[cfile, "    },\n\n"];

(* Real part numerical values *)
(* first produce namelist of scalar input parameters *)
par = Map[ Re, parlist, {2} ] /. Re[aa_] -> aa;
ind = Level[#, 1] & /@ Keys[par];
sind = Map[ToString, #, 2] & /@ ind;
sind =  "Re" <> ToString[wcname] <> StringJoin[#] & /@ sind;
sind = Rule @@@ ({wcname @@@ ind, sind} // Transpose);
par = par /. sind;

Module[{},
  WriteLine[cfile, " " <> Keys[#] <> " == {"];
  WriteLine[cfile, "    ParameterType    -> External,"];
  WriteLine[cfile, "    InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
  WriteLine[cfile, "    Value            -> " <> NumberToString[Keys[#] /. par] <> "," ];
  WriteLine[cfile, "    ComplexParameter -> False,"];
  WriteLine[cfile, "    TeX              -> Superscript[" <> SMEFT$MB <> ", " <>
                                            StringReplace[ name, "phi"->"\[Phi]" ] <> "],"];
  WriteLine[cfile, "    Description      -> \"Real part of " <> StringDrop[Keys[#],2] <>
                   " WC\""];
  WriteLine[cfile, "    },\n\n"];
] & /@ par;

(* Imaginary part numerical values *)
(* first produce namelist of scalar input parameters *)
sind = Map[ToString, #, 2] & /@ ind;
sind =  "Im" <> ToString[wcname] <> StringJoin[#] & /@ sind;
sind = Rule @@@ ({wcname @@@ ind, sind} // Transpose);
par = Map[ Im, parlist, {2} ] /. Im[aa_] -> aa /. sind;
(* generate only entries for non-vanishing Im parts *)
If[ Values[#] != 0,
  WriteLine[cfile, " " <> Keys[#] <> " == {"];
  WriteLine[cfile, "    ParameterType    -> External,"];
  WriteLine[cfile, "    InteractionOrder -> {NP," <> ToString[ SMEFT$NPOrder[name], InputForm ] <> "},"];
  WriteLine[cfile, "    Value            -> " <> NumberToString[Keys[#] /. par] <> "," ];
  WriteLine[cfile, "    ComplexParameter -> False,"];
  WriteLine[cfile, "    TeX              -> Superscript[" <> SMEFT$MB <> ", " <>
                                            StringReplace[ name, "phi"->"\[Phi]" ] <> "],"];
  WriteLine[cfile, "    Description      -> \"Imaginary part of " <> StringDrop[Keys[#],2] <>
                   " WC\""];
  WriteLine[cfile, "    },\n\n"];
] & /@ par;

]
(* end of WriteUFOTensorEntry *)			
]




WriteMixingEntry = Function[{cfile,wc},
(* par file entry for generic CKM and PMNS matrices *)
(* wc argument is association wcname->wcvalue(s) *)
Module[{WC,name},

name = ToString[ Keys[wc] ];
WC = Values[wc];

WriteLine[cfile, " " <> name <> " == {"];
WriteLine[cfile, "    ParameterType    -> External,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]},"];
WriteLine[cfile, TensorOutputFormat[ ToString /@ Keys[WC], NumberToString /@ Values[WC] ] ];
WriteLine[cfile, "    Unitary          -> True,"];
WriteLine[cfile, "    TeX              -> " <> StringTake[name,1] <> ","];
WriteLine[cfile, "    Description      -> \"" <> If[ name === "Kq", "CKM", "PMNS" ] <> " matrix\""];
WriteLine[cfile, "    },\n\n"];

]
(* end of WriteMixingEntry *)
]




WriteDiagonalMixingEntry = Function[{cfile,wc},
(* par file entry for diagonal CKM and PMNS matrices *)
(* wc argument is association wcname->wcvalue(s) *)
Module[{name},

name = ToString[ Keys[wc] ];

WriteLine[cfile, " " <> name <> " == {"];
WriteLine[cfile, "    ParameterType    -> Internal,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]},"];
WriteLine[cfile, "    Definitions      -> {" <> name <> "[ff1_,ff2_] -> IndexDelta[ff1,ff2]},"];
WriteLine[cfile, "    TeX              -> " <> StringTake[name,1] <> ","];
WriteLine[cfile, "    Description      -> \"" <> If[ name === "Kq", "CKM", "PMNS" ] <> " matrix\""];
WriteLine[cfile, "    },\n\n"];

]
(* end of WriteDiagonalMixingEntry *)
]




WriteRealMixingEntry = Function[{cfile,wc},
(* par file entry for real only CKM and PMNS matrices *)
(* wc argument is association wcname->wcvalue(s) *)
Module[{WC,name},

name = ToString[ Keys[wc] ];
WC = Values[wc];

WriteLine[cfile, " " <> name <> " == {"];
WriteLine[cfile, "    ParameterType    -> External,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]},"];
WriteLine[cfile, TensorOutputFormat[ ToString /@ Keys[WC], NumberToString /@ Values[WC] ] ];
WriteLine[cfile, "    ComplexParameter -> False,"];
WriteLine[cfile, "    TeX              -> " <> StringTake[name,1] <> ","];
WriteLine[cfile, "    Description      -> \"" <> If[ name === "Kq", "CKM", "PMNS" ] <> " matrix\""];
WriteLine[cfile, "    },\n\n"];

]
(* end of WriteRealMixingEntry *)			
]



WriteComplexCKMEntry = Function[{cfile,wc},
(* par file entry for complex CKM matrix *)
(* wc argument is association wcname->wcvalue(s) *)
Module[{WC,name,wcval,ind,tmp,i},

name = ToString[ Keys[wc] ];
WC = Values[wc];

(* create list of scalar parameters *)
wcval = {};
For[ i=1, i < Length[WC] + 1, i++,
  tmp = WC[[i]];
  ind = StringJoin[ ToString /@ Level[Keys[tmp], 1] ];
  AppendTo[ wcval, ToExpression[ "Re" <> name <> ind <>
                   "->" <> ToString[ Re[Values[tmp]], InputForm] ] ];
  If [ MemberQ[ {"13","21","31","32"}, ind ],
    AppendTo[ wcval, ToExpression[ "Im" <> name <> ind <>
                     "->" <> ToString[Im[Values[tmp]], InputForm]] ];
  ];
];

(* split matrix into Re and Im parts *)
WriteLine[cfile, " " <> name <> " == {"];
WriteLine[cfile, "    ParameterType    -> Internal,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]},"];
WriteLine[cfile, "    Definitions      -> {Kq[1, 1] -> ReKq11,
                         Kq[1, 2] -> ReKq12,
                         Kq[1, 3] -> ReKq13 + I ImKq13,
                         Kq[2, 1] -> ReKq21 + I ImKq21,
                         Kq[2, 2] -> ReKq22,
                         Kq[2, 3] -> ReKq23,
                         Kq[3, 1] -> ReKq31 + I ImKq31,
                         Kq[3, 2] -> ReKq32 + I ImKq32,
                         Kq[3, 3] -> ReKq33},"];
(*                         Kq[3, 3] -> 0.999},"];*)

WriteLine[cfile, "    ComplexParameter -> True,"];
WriteLine[cfile, "    TeX              -> K,"];
WriteLine[cfile, "    Description      -> \"CKM matrix\""];
WriteLine[cfile, "    },\n\n"];

(* Store numerical values, for Im only non-vanishing entries *)
Module[{},
  tmp = ToString[Keys[#]];
  WriteLine[cfile, " " <> tmp <> " == {"];
  WriteLine[cfile, "    ParameterType    -> External,"];
  WriteLine[cfile, "    Value            -> " <> NumberToString[Keys[#] /. wcval] <> "," ];
  WriteLine[cfile, "    ComplexParameter -> False,"];
  WriteLine[cfile, "    TeX              -> " <> StringDrop[ tmp, -4]  <> " Subscript[K," <>
                                                 StringDrop[ tmp, 4 ] <> "],"];
  WriteLine[cfile, "    Description      -> \"" <> StringDrop[ tmp, -4] <> " part of K_" <>
                        StringDrop[ tmp, 4 ] <> "\""];
  WriteLine[cfile, "    },\n\n"];
] & /@ wcval;

]
(* end of WriteComplexCKMEntry *)			
]



WriteComplexPMNSEntry = Function[{cfile,wc},
(* par file entry for complex PMNS matrix *)
(* wc argument is association wcname->wcvalue(s) *)
Module[{wcr,wci,aa},

wcr = Map[Re, Values[wc], {2}] /. Re[aa_] -> aa /. Ul -> ReUl;
wci = Map[Im, Values[wc], {2}] /. Im[aa_] -> aa /. Ul -> ImUl;

(* split matrix into Re and Im parts *)
WriteLine[cfile, " Ul == {"];
WriteLine[cfile, "    ParameterType    -> Internal,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]},"];
WriteLine[cfile, "    Definitions      -> {Ul[ff1_,ff2_] -> ReUl[ff1,ff2] + I ImUl[ff1,ff2]},"];
WriteLine[cfile, "    ComplexParameter -> True,"];
WriteLine[cfile, "    TeX              -> U,"];
WriteLine[cfile, "    Description      -> \"PMNS matrix\""];
WriteLine[cfile, "    },\n\n"];

(* Real part numerical values *)
WriteLine[cfile, " ReUl == {"];
WriteLine[cfile, "    ParameterType    -> External,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]},"];
WriteLine[cfile, TensorOutputFormat[ ToString /@ Keys[wcr], NumberToString /@ Values[wcr] ] ];
WriteLine[cfile, "    ComplexParameter -> False,"];
WriteLine[cfile, "    TeX              -> Re(U),"];
WriteLine[cfile, "    Description      -> \"Real part of PMNS matrix\""];
WriteLine[cfile, "    },\n\n"];

(* Imaginary part numerical values *)
WriteLine[cfile, " ImUl == {"];
WriteLine[cfile, "    ParameterType    -> External,"];
WriteLine[cfile, "    Indices          -> {Index[Generation], Index[Generation]},"];
WriteLine[cfile, "    InteractionOrder -> {CP,1},"];
WriteLine[cfile, TensorOutputFormat[ ToString /@ Keys[wci], NumberToString /@ Values[wci] ] ];
WriteLine[cfile, "    ComplexParameter -> False,"];
WriteLine[cfile, "    TeX              -> Im(U),"];
WriteLine[cfile, "    Description      -> \"Imaginary part of PMNS matrix\""];
WriteLine[cfile, "    },\n\n"];

]
(* end of WriteComplexPMNSEntry *)			
]




TensorOutputFormat = Function[{wcname,wcval},
(* formats nicely output of tensor parameter numerical values in model files *)
Module[{i, len, tmp, sub},

len = Length[wcname];
sub = Table[ If[ i > 1, "                         ", "" ] <> wcname[[i]] <>
             " -> " <> wcval[[i]], {i,1,len} ];

tmp = "    Value            -> {" <> sub[[1]] <> ",\n";
For[i=2, i < len, i++, tmp = tmp <> sub[[i]]  <> ",\n" ];
tmp = tmp <> sub[[len]] <> "},";

tmp

]
(* end of TensorOutputFormat *)
];



TensorSubFormat = Function[{sublist1,sublist2},
(* formats nicely output of tensor parameter replacements in model
files; sublist1 is list of independent parameters, sublist2 are
dependent parameters *)
Module[{i, len1, len2, tmp, sub, spc},

len1 = Length[sublist1];
len2 = Length[sublist2];

sub = {};
(*  replacement list WC -> Re or Re + i Im for independent parameters *)
For[ i=1, i < len1 + 1, i++,
  tmp = Keys[sublist1][[i]];
  If [ RealValuedNumberQ[ Values[sublist1][[i]] ],
    AppendTo[ sub, tmp -> ToExpression[ "Re" <> ToString[ Head[tmp] ] <> StringJoin[ ToString /@ Level[tmp, 1] ] ] ];
  ,
    AppendTo[ sub, tmp -> ToExpression[ "Re" <>
         ToString[ Head[tmp] ] <> StringJoin[ ToString /@ Level[tmp, 1] ] <>
         " + I Im" <> ToString[ Head[tmp] ] <> StringJoin[ ToString /@ Level[tmp, 1] ] ] ];
  ];
];

(* add dependent parameters to list *)
tmp = sublist2 /. sub /. Conjugate[spc_]->spc;
sub = Union[sub,tmp];

(* create output string *)
spc = "                         ";
tmp = "    Definitions      -> {" <> ToString[ sub[[1]], InputForm] <> ",\n";
For[i=2, i < len1 + len2, i++, tmp = tmp <> spc <> ToString[ sub[[i]], InputForm] <> ",\n" ];
tmp = tmp <> spc <> ToString[ sub[[len1 + len2]], InputForm] <> "},";

tmp = StringReplace[tmp, "(-I)"->"-I"];
StringReplace[tmp, "*"->" "]

]
(* end of TensorSubFormat *)
];
